// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("AbsenceOrder")]
    public partial class AbsenceOrder
    {
        [Key]
        public int AbsenceID { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string AbsenceOrderStartDate { get; set; }
        public double? AbsenceAmount { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        [StringLength(50)]
        public string ReDate { get; set; }
        [StringLength(50)]
        public string AbsenceOrderEndDate { get; set; }
        public int? CountAbsentNo { get; set; }
        public int? TypeID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("AbsenceOrders")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}