// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class AdministrativeDecision
    {
        [Key]
        public int ID { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string DecisionsIss { get; set; }
        [Column(TypeName = "ntext")]
        public string DecisionsAll { get; set; }
        [StringLength(50)]
        public string DecisionsDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("AdministrativeDecisions")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}