// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("AllInvoicesDetailsPayment")]
    public partial class AllInvoicesDetailsPayment
    {
        [Key]
        public int ID { get; set; }
        public int? BranchID { get; set; }
        public int? FinancialID { get; set; }
        public int? InvoiceCode { get; set; }
        public int? InvoiceID { get; set; }
        [StringLength(100)]
        public string NameSales { get; set; }
        [StringLength(50)]
        public string MobileSales { get; set; }
        [StringLength(50)]
        public string MobileCustomer { get; set; }
        [StringLength(50)]
        public string AccCashID { get; set; }
        [StringLength(50)]
        public string AccCheckID { get; set; }
        [Column(TypeName = "money")]
        public decimal? PaymentInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? RemainInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountCash { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountVBank { get; set; }
        public int? FrmValue { get; set; }
        [StringLength(50)]
        public string CheckNo { get; set; }
        [StringLength(50)]
        public string CheckDate { get; set; }
        [StringLength(200)]
        public string AddressSales { get; set; }
        [StringLength(200)]
        public string AddressCustomer { get; set; }
        [StringLength(50)]
        public string CardNoCustomer { get; set; }
        [Column(TypeName = "money")]
        public decimal? PaymentAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? RemainAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? ChangeAmount { get; set; }
        [StringLength(50)]
        public string AccChangeID { get; set; }
        [Column(TypeName = "money")]
        public decimal? PointAmount { get; set; }
        public double? ComissCard { get; set; }
        public double? NetInvFc { get; set; }
        public double? Transfer { get; set; }
        public int? CurrencyID { get; set; }
        [StringLength(250)]
        public string AmountCashNote { get; set; }
        [StringLength(250)]
        public string AmountVBankNote { get; set; }
        [StringLength(250)]
        public string ChangeAmountNote { get; set; }
        [StringLength(250)]
        public string AmountPointNote { get; set; }
        public int? RetunChangeID { get; set; }
        public double? QtyAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountCashpay { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("CurrencyID")]
        [InverseProperty("AllInvoicesDetailsPayments")]
        public virtual Currency Currency { get; set; }
    }
}