// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class AllInvoiceJion
    {
        [Key]
        public int ID { get; set; }
        public int? InvoiceCode { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? NoteID { get; set; }
        [StringLength(100)]
        public string ItemNote { get; set; }
        [Column(TypeName = "money")]
        public decimal? NotesPrice { get; set; }
        public double? NotesQty { get; set; }
        public int? BranchID { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalN { get; set; }
        public double? TaxN { get; set; }
        public double? Cip { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("ItemID")]
        [InverseProperty("AllInvoiceJions")]
        public virtual Item Item { get; set; }
        [ForeignKey("NoteID")]
        [InverseProperty("AllInvoiceJions")]
        public virtual MainDatum Note { get; set; }
    }
}