// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class AllInvoicesDetail
    {
        [Key]
        public int ID { get; set; }
        public int? InvoiceCode { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? UnitID { get; set; }
        public int? WarehouseID { get; set; }
        public double? Quantity { get; set; }
        public double? QuantityBouns { get; set; }
        public double? QuantityFull { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? DiscountDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? CostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? OtherPrice { get; set; }
        [StringLength(50)]
        public string OfferItem { get; set; }
        [Column(TypeName = "ntext")]
        public string SerialNo { get; set; }
        [Column(TypeName = "ntext")]
        public string NotesItem { get; set; }
        [StringLength(50)]
        public string ProductItem { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxDetails { get; set; }
        public double? TaxPerItem { get; set; }
        [Column(TypeName = "money")]
        public decimal? CiTax { get; set; }
        [Column(TypeName = "ntext")]
        public string ItemNote { get; set; }
        [StringLength(50)]
        public string ProductItemPOS { get; set; }
        public double? StoneWeight { get; set; }
        public double? TotalQty { get; set; }
        public int? MDCodeSubGroup { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [StringLength(150)]
        public string Batch { get; set; }
        [StringLength(150)]
        public string Personality { get; set; }
        [StringLength(50)]
        public string ItemAccID { get; set; }
        [Column(TypeName = "money")]
        public decimal? PriceBeforeTax { get; set; }
        [Column(TypeName = "money")]
        public decimal? OtherDiscount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpireDate { get; set; }

        [ForeignKey("InvoiceCode")]
        [InverseProperty("AllInvoicesDetails")]
        public virtual AllInvoice InvoiceCodeNavigation { get; set; }
        [ForeignKey("ItemID")]
        [InverseProperty("AllInvoicesDetails")]
        public virtual Item Item { get; set; }
        [ForeignKey("UnitID")]
        [InverseProperty("AllInvoicesDetails")]
        public virtual MainDatum Unit { get; set; }
        [ForeignKey("WarehouseID")]
        [InverseProperty("AllInvoicesDetails")]
        public virtual BranchsAndWarehouse Warehouse { get; set; }
    }
}