// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class AllInvoiceImage
    {
        [Key]
        public int ID { get; set; }
        public int InvoiceCode { get; set; }
        public int? FrmValue { get; set; }
        [Column(TypeName = "image")]
        public byte[] InvoiceImage { get; set; }
        public string ImagePath { get; set; }
        [StringLength(15)]
        public string DateImages { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string For { get; set; }
    }
}