// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class AllInvoice
    {
        public AllInvoice()
        {
            AllInvoicesDetails = new HashSet<AllInvoicesDetail>();
        }

        public int InID { get; set; }
        [Key]
        public int InvoiceCode { get; set; }
        public int? InvoiceID { get; set; }
        public int? CashierID { get; set; }
        public int? BranchID { get; set; }
        public int? PrCuID { get; set; }
        public int? UserID { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DueDate { get; set; }
        [StringLength(50)]
        public string ProvInvNo { get; set; }
        [StringLength(50)]
        public string ProvInvDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? DiscountInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetInv { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        public bool? Done { get; set; }
        public int? UpdatePrice { get; set; }
        public int? PayType { get; set; }
        public int? OrderPurchase { get; set; }
        public int? FrmValue { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        public int? PriceID { get; set; }
        public int? QutationID { get; set; }
        public int? ReturnInvoiceID { get; set; }
        [StringLength(50)]
        public string DateEnd { get; set; }
        public int? SalesManCode { get; set; }
        public bool? BookMark { get; set; }
        [Column(TypeName = "money")]
        public decimal? PofitInvoice { get; set; }
        [Column(TypeName = "money")]
        public decimal? BonusPercent { get; set; }
        public int? CopyNo { get; set; }
        [StringLength(50)]
        public string TimeIN { get; set; }
        public int? CostCenterID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? CarID { get; set; }
        [StringLength(50)]
        public string EmployeeID { get; set; }
        public int? PostionID { get; set; }
        public int? DeliveryID { get; set; }
        public int? PointActive { get; set; }
        public int? OrderPosNo { get; set; }
        public int? TablePosNo { get; set; }
        public int? TypeOrderPos { get; set; }
        public int? TypeReturn { get; set; }
        [StringLength(50)]
        public string DateDelivery { get; set; }
        [StringLength(50)]
        public string TimeDelivery { get; set; }
        public int? BookingID { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        public double? PerTaxAmount { get; set; }
        [StringLength(50)]
        public string PCTaxNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? CigaretTax { get; set; }
        public double? PerCigaretTax { get; set; }
        public int? e_InvNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? RoundNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? AllwedDiscount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InvSaveDate { get; set; }
        [StringLength(50)]
        public string InvoiceQR { get; set; }
        public int? e_InvType { get; set; }
        public int? e_InvStatus { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("AllInvoices")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("BranchID")]
        [InverseProperty("AllInvoices")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("CashierID")]
        [InverseProperty("AllInvoices")]
        public virtual MainDatum Cashier { get; set; }
        [ForeignKey("FinancialID")]
        [InverseProperty("AllInvoices")]
        public virtual FinancialYear Financial { get; set; }
        [ForeignKey("SalesManCode")]
        [InverseProperty("AllInvoices")]
        public virtual SalesManInfo SalesManCodeNavigation { get; set; }
        [ForeignKey("UserID")]
        [InverseProperty("AllInvoices")]
        public virtual AspNetUser User { get; set; }
        [InverseProperty("InvoiceCodeNavigation")]
        public virtual ICollection<AllInvoicesDetail> AllInvoicesDetails { get; set; }
    }
}