// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class AllVouchersDetail
    {
        [Key]
        public int ID { get; set; }
        public int? VoucherID { get; set; }
        [StringLength(50)]
        public string ToAccID { get; set; }
        [Column(TypeName = "ntext")]
        public string VoucherDescriptions { get; set; }
        [Column(TypeName = "money")]
        public decimal? VoucherAmount { get; set; }
        public int? TypeDoc { get; set; }
        public int? InvoiceNo { get; set; }
        public int? CostCenterID { get; set; }
        public int? BankID { get; set; }
        [StringLength(50)]
        public string CheckNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckDate { get; set; }
        public double? TaxAmountExp { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TaxNo { get; set; }
        public bool? TaxState { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetDetails { get; set; }
        public int? PrCuID { get; set; }

        [ForeignKey("ToAccID")]
        [InverseProperty("AllVouchersDetails")]
        public virtual TreeAccount ToAcc { get; set; }
    }
}