// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Index("NormalizedEmail", Name = "EmailIndex")]
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            AllInvoices = new HashSet<AllInvoice>();
            AllVouchers = new HashSet<AllVoucher>();
            AspNetUserClaims = new HashSet<AspNetUserClaim>();
            AspNetUserLogins = new HashSet<AspNetUserLogin>();
            AspNetUserRoles = new HashSet<AspNetUserRole>();
            AspNetUserTokens = new HashSet<AspNetUserToken>();
            FxiedAssets = new HashSet<FxiedAsset>();
        }

        [Key]
        public int UserID { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        public int? DiscountCash { get; set; }
        public int? DiscountCredit { get; set; }
        public bool? NoActive { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        public int? TypeUser { get; set; }
        public int? MinuteWait { get; set; }
        [StringLength(100)]
        public string UserNameEng { get; set; }
        [StringLength(256)]
        public string NormalizedUserName { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        [StringLength(256)]
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        [StringLength(500)]
        public string LogoURL { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<AllInvoice> AllInvoices { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<AllVoucher> AllVouchers { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<AspNetUserToken> AspNetUserTokens { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<FxiedAsset> FxiedAssets { get; set; }
    }
}