// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("AttendanceEmployessAutomated")]
    public partial class AttendanceEmployessAutomated
    {
        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [Key]
        [StringLength(20)]
        public string DateInsert { get; set; }
        [Key]
        [StringLength(20)]
        public string TimeInsert { get; set; }
        public int? Type { get; set; }
        public bool? Done { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}