// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("BonusOrder")]
    public partial class BonusOrder
    {
        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string BonusOrderNo { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string BonusOrderDate { get; set; }
        public int? BonusType { get; set; }
        [Column(TypeName = "money")]
        public decimal? BonusAmount { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        [StringLength(50)]
        public string AddBounsDate { get; set; }
        [StringLength(50)]
        public string AccFundID { get; set; }
        public bool? ChekAdd { get; set; }
        public bool? Done { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccFundID")]
        [InverseProperty("BonusOrders")]
        public virtual TreeAccount AccFund { get; set; }
        [ForeignKey("EmployeeCode")]
        [InverseProperty("BonusOrders")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}