// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class CarsDatum
    {
        public int ID { get; set; }
        [Key]
        public int NoID { get; set; }
        public int? EmployeeCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LicenseDate { get; set; }
        [StringLength(50)]
        public string PlantNo { get; set; }
        [StringLength(50)]
        public string SturchNo { get; set; }
        [StringLength(50)]
        public string TypeCar { get; set; }
        [StringLength(50)]
        public string ColorCar { get; set; }
        public int? ModelCar { get; set; }
        [StringLength(100)]
        public string Owner { get; set; }
        [StringLength(50)]
        public string StratFDate { get; set; }
        [StringLength(50)]
        public string EndFDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StratFDateG { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndFDateG { get; set; }
        public double? InsAmount { get; set; }
        [StringLength(100)]
        public string InsCompany { get; set; }
        [StringLength(50)]
        public string StratIDate { get; set; }
        [StringLength(50)]
        public string EndIDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StratIDateG { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndIDateG { get; set; }
        [StringLength(255)]
        public string CarName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("CarsData")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}