// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ChecksInventory")]
    public partial class ChecksInventory
    {
        [Key]
        public int ID { get; set; }
        [Column(TypeName = "money")]
        public decimal? Amount { get; set; }
        [Column(TypeName = "ntext")]
        public string Details { get; set; }
        public int? BranchID { get; set; }
        public int? FileYearID { get; set; }
        [StringLength(50)]
        public string DateDayin { get; set; }
        public int? Number { get; set; }
        [StringLength(50)]
        public string GroupName { get; set; }
        public int? UserID { get; set; }
        public int? SalesManCode { get; set; }
        public int? CashierID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}