// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ComissionBankCard")]
    public partial class ComissionBankCard
    {
        [Key]
        public int ID { get; set; }
        public double? DefaultComiss { get; set; }
        public double? DefaultToAmount { get; set; }
        public int? DefaultTypeCash { get; set; }
        [StringLength(50)]
        public string DefaultCardType { get; set; }
        [StringLength(500)]
        public string DefaultImage { get; set; }
        public double? DefaultcomAmount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}