// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ComissionBank")]
    public partial class ComissionBank
    {
        [Key]
        public int ID { get; set; }
        public double? Comiss { get; set; }
        public double? ToAmount { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? BranchID { get; set; }
        public int? FundID { get; set; }
        public int? TypeCash { get; set; }
        [StringLength(50)]
        public string CardType { get; set; }
        public double? comAmount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [StringLength(500)]
        public string Image { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("ComissionBanks")]
        public virtual TreeAccount Acc { get; set; }
    }
}