// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("CompanyInformation")]
    public partial class CompanyInformation
    {
        [Key]
        public int CompanyCode { get; set; }
        [StringLength(100)]
        public string CINameArb { get; set; }
        public int? CountryID { get; set; }
        public int? CityID { get; set; }
        [StringLength(100)]
        public string CIAddressArb { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(50)]
        public string Emails { get; set; }
        [StringLength(50)]
        public string PBox { get; set; }
        [StringLength(100)]
        public string CINameEng { get; set; }
        [StringLength(100)]
        public string CIAddressEng { get; set; }
        [StringLength(50)]
        public string CIVATNo { get; set; }
        [StringLength(50)]
        public string CITradReg { get; set; }
        [StringLength(50)]
        public string CIAccBank { get; set; }
        [StringLength(50)]
        public string ZipNo { get; set; }
        [StringLength(50)]
        public string AddtionalNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [StringLength(500)]
        public string Image { get; set; }

        [ForeignKey("CityID")]
        [InverseProperty("CompanyInformations")]
        public virtual City City { get; set; }
    }
}