// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("CostProduction")]
    public partial class CostProduction
    {
        public CostProduction()
        {
            DistributionExpenses = new HashSet<DistributionExpense>();
            ExpensesProductions = new HashSet<ExpensesProduction>();
        }

        public int ID { get; set; }
        [Key]
        public int CostNo { get; set; }
        [StringLength(100)]
        public string CostName { get; set; }
        public int? CostStats { get; set; }
        public double? CostPercent { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("CostProductions")]
        public virtual TreeAccount Acc { get; set; }
        [InverseProperty("Cost")]
        public virtual ICollection<DistributionExpense> DistributionExpenses { get; set; }
        [InverseProperty("CostNoNavigation")]
        public virtual ICollection<ExpensesProduction> ExpensesProductions { get; set; }
    }
}