// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("Currency")]
    public partial class Currency
    {
        public Currency()
        {
            AllInvoicesDetailsPayments = new HashSet<AllInvoicesDetailsPayment>();
        }

        public int ID { get; set; }
        [Key]
        public int CurrencyID { get; set; }
        [StringLength(50)]
        public string CurrencyName { get; set; }
        [StringLength(30)]
        public string CurrencyCode { get; set; }
        [StringLength(10)]
        public string CurrencyPart { get; set; }
        [Column(TypeName = "money")]
        public decimal? TransferRateGeneral { get; set; }
        public int? LocalOrForiegn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [InverseProperty("Currency")]
        public virtual ICollection<AllInvoicesDetailsPayment> AllInvoicesDetailsPayments { get; set; }
    }
}