// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class CustomersPoint
    {
        [Key]
        public int ID { get; set; }
        public int? PoCustomerNo { get; set; }
        [StringLength(100)]
        public string PoCustomerName { get; set; }
        [StringLength(200)]
        public string PoCustomerAddress { get; set; }
        [StringLength(50)]
        public string PoCustomerEmail { get; set; }
        public int? PoCustomerType { get; set; }
        [StringLength(50)]
        public string PoCustomerCardNo { get; set; }
        [StringLength(50)]
        public string PoCustomerMobile { get; set; }
        [Column(TypeName = "ntext")]
        public string PoCustomerNotes { get; set; }
        [StringLength(50)]
        public string PoDateCreate { get; set; }
        public int? PoBranchNo { get; set; }
        public double? PoOpenBalance { get; set; }
        public double? PoMoveBalance { get; set; }
        public double? PoCurrentBalance { get; set; }
        public double? CurrentPoint { get; set; }
        [StringLength(50)]
        public string TaxNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}