// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("DeductionOrder")]
    public partial class DeductionOrder
    {
        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string DeductionOrderNo { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string DeductionOrderDate { get; set; }
        public int? DeductionType { get; set; }
        [Column(TypeName = "money")]
        public decimal? DeductionAmount { get; set; }
        [StringLength(50)]
        public string Note { get; set; }
        [StringLength(50)]
        public string DeductionForDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("DeductionOrders")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}