// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class DistributionExpense
    {
        [Key]
        public int ID { get; set; }
        public int InvoiceCode { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        [StringLength(50)]
        public string TimeIN { get; set; }
        [StringLength(50)]
        public string FromDate { get; set; }
        [StringLength(50)]
        public string ToDate { get; set; }
        public string Note { get; set; }
        public double? CostAmount { get; set; }
        [Column(TypeName = "ntext")]
        public string CostNotes { get; set; }
        public double? CostPerValue { get; set; }
        public int? BranchID { get; set; }
        public int? CostID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? DisType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("DistributionExpenses")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("BranchID")]
        [InverseProperty("DistributionExpenses")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("CostID")]
        [InverseProperty("DistributionExpenses")]
        public virtual CostProduction Cost { get; set; }
    }
}