// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("EmployeeCosting")]
    public partial class EmployeeCosting
    {
        [Key]
        public int ID { get; set; }
        public int? ContractID { get; set; }
        public int EmployeeCode { get; set; }
        public int? TypeDocument { get; set; }
        [StringLength(50)]
        public string DateType { get; set; }
        public double? AmountMonth { get; set; }
        public double? AmountMonthDay { get; set; }
        [StringLength(50)]
        public string DateYear { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("EmployeeCostings")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}