// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("EmployessPeriod")]
    public partial class EmployessPeriod
    {
        [Key]
        public int ID { get; set; }
        [StringLength(10)]
        public string PeriodID { get; set; }
        [StringLength(50)]
        public string FromTime { get; set; }
        [StringLength(50)]
        public string ToTime { get; set; }
        [StringLength(50)]
        public string Hourse { get; set; }
        public int? EmployeeCode { get; set; }
        public int? PeriodNo { get; set; }
        public double? HourseAll { get; set; }
        public double? AveBouns { get; set; }
        public double? AveAbsen { get; set; }
        public double? AveLeat { get; set; }
        public int? MuLeat { get; set; }
        [StringLength(50)]
        public string FromTime24 { get; set; }
        [StringLength(50)]
        public string ToTime24 { get; set; }
        public int? minutes { get; set; }
        public int? DayID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("EmployessPeriods")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}