// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("EmpLang")]
    public partial class EmpLang
    {
        [Key]
        public int EmpLangID { get; set; }
        public int? EmployeeCode { get; set; }
        public int? LanguageID { get; set; }
        public int? LangSkillLevelID { get; set; }
        public double? LangYearsOfExperience { get; set; }
        [StringLength(50)]
        public string LangLastUsed { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("EmpLangs")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}