// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("EmployeeCategory")]
    public partial class EmployeeCategory
    {
        public int ID { get; set; }
        [Key]
        public int CategoryID { get; set; }
        [StringLength(50)]
        public string CategoryNameA { get; set; }
        [StringLength(50)]
        public string CategoryNameE { get; set; }
        /// <summary>
        /// 0=Annually, 1=Monthly, 2=Daily
        /// </summary>
        [StringLength(100)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}