// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class EmployeesDetail
    {
        public EmployeesDetail()
        {
            AbsenceOrders = new HashSet<AbsenceOrder>();
            AdministrativeDecisions = new HashSet<AdministrativeDecision>();
            AttendanceEmployessPeriods = new HashSet<AttendanceEmployessPeriod>();
            BonusOrders = new HashSet<BonusOrder>();
            CarsData = new HashSet<CarsDatum>();
            Contracts = new HashSet<Contract>();
            DeductionDetails = new HashSet<DeductionDetail>();
            DeductionOrders = new HashSet<DeductionOrder>();
            Deductions = new HashSet<Deduction>();
            Documents = new HashSet<Document>();
            EmpLangs = new HashSet<EmpLang>();
            EmployeeCostings = new HashSet<EmployeeCosting>();
            EmployeesDetailsFamilies = new HashSet<EmployeesDetailsFamily>();
            EmployessPeriods = new HashSet<EmployessPeriod>();
            Experiences = new HashSet<Experience>();
            InstallmentMonthlies = new HashSet<InstallmentMonthly>();
            LeaveOrders = new HashSet<LeaveOrder>();
            Loans = new HashSet<Loan>();
            LoansDetails = new HashSet<LoansDetail>();
            LoansForms = new HashSet<LoansForm>();
            OhdaOrders = new HashSet<OhdaOrder>();
            OverTimeOrders = new HashSet<OverTimeOrder>();
            PassportData = new HashSet<PassportDatum>();
            PayRolls = new HashSet<PayRoll>();
            PermissionExits = new HashSet<PermissionExit>();
            PromotionJobs = new HashSet<PromotionJob>();
            PromotionSalaries = new HashSet<PromotionSalary>();
            SettlementEmps = new HashSet<SettlementEmp>();
            Skills = new HashSet<Skill>();
            SocialnsuranceAmounts = new HashSet<SocialnsuranceAmount>();
            Tickets = new HashSet<Ticket>();
            Training = new HashSet<Training>();
        }

        public int EmployeeID { get; set; }
        [Key]
        public int EmployeeCode { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(30)]
        public string Passwords { get; set; }
        public int? GenderID { get; set; }
        [StringLength(50)]
        public string DOBHI { get; set; }
        [StringLength(50)]
        public string DOBGR { get; set; }
        public int? ReligionID { get; set; }
        public int? BloodType { get; set; }
        public int? Qualification { get; set; }
        [StringLength(50)]
        public string Major { get; set; }
        public int? Nationality { get; set; }
        public int? MaritalStatus { get; set; }
        [StringLength(50)]
        public string Dependents { get; set; }
        [StringLength(50)]
        public string PassportNo { get; set; }
        [StringLength(50)]
        public string PassportExpires { get; set; }
        [StringLength(50)]
        public string NationalNo { get; set; }
        [StringLength(50)]
        public string NationalExpires { get; set; }
        [StringLength(50)]
        public string ResidenceNo { get; set; }
        [StringLength(50)]
        public string ResidenceExpires { get; set; }
        [StringLength(50)]
        public string DrivingLicNo { get; set; }
        [StringLength(50)]
        public string DrivingLicExpires { get; set; }
        [StringLength(50)]
        public string MedicalInsurance { get; set; }
        [StringLength(50)]
        public string MedicalInsExpires { get; set; }
        [StringLength(50)]
        public string SocialInsurance { get; set; }
        [StringLength(50)]
        public string BankName { get; set; }
        [StringLength(50)]
        public string BankAccountNo { get; set; }
        [StringLength(100)]
        public string AddressA { get; set; }
        [StringLength(100)]
        public string AddressE { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(100)]
        public string SponsorName { get; set; }
        [StringLength(50)]
        public string SponsorPhone { get; set; }
        [StringLength(100)]
        public string SponsorAddress { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        public int? DepartmentID { get; set; }
        public int? ProfessionsID { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        [StringLength(50)]
        public string HireDate { get; set; }
        public int? CategoryID { get; set; }
        [StringLength(50)]
        public string JobID { get; set; }
        [Column(TypeName = "ntext")]
        public string PermissionString { get; set; }
        public int? Status { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(1000)]
        public string EmpImage { get; set; }
        [StringLength(50)]
        public string AccIDDe { get; set; }
        [StringLength(50)]
        public string AccIDE { get; set; }
        [StringLength(50)]
        public string AccIDO { get; set; }
        public bool? ChType { get; set; }
        [StringLength(50)]
        public string AccIDL { get; set; }
        public int? TypeEm { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccIDDe")]
        [InverseProperty("EmployeesDetailAccIDDeNavigations")]
        public virtual TreeAccount AccIDDeNavigation { get; set; }
        [ForeignKey("AccIDE")]
        [InverseProperty("EmployeesDetailAccIDENavigations")]
        public virtual TreeAccount AccIDENavigation { get; set; }
        [ForeignKey("AccIDL")]
        [InverseProperty("EmployeesDetailAccIDLNavigations")]
        public virtual TreeAccount AccIDLNavigation { get; set; }
        [ForeignKey("AccIDO")]
        [InverseProperty("EmployeesDetailAccIDONavigations")]
        public virtual TreeAccount AccIDONavigation { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual OpenBalanceLeave OpenBalanceLeave { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<AbsenceOrder> AbsenceOrders { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<AdministrativeDecision> AdministrativeDecisions { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<AttendanceEmployessPeriod> AttendanceEmployessPeriods { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<BonusOrder> BonusOrders { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<CarsDatum> CarsData { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<DeductionDetail> DeductionDetails { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<DeductionOrder> DeductionOrders { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Deduction> Deductions { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Document> Documents { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<EmpLang> EmpLangs { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<EmployeeCosting> EmployeeCostings { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<EmployeesDetailsFamily> EmployeesDetailsFamilies { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<EmployessPeriod> EmployessPeriods { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Experience> Experiences { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<InstallmentMonthly> InstallmentMonthlies { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<LeaveOrder> LeaveOrders { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Loan> Loans { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<LoansDetail> LoansDetails { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<LoansForm> LoansForms { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<OhdaOrder> OhdaOrders { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<OverTimeOrder> OverTimeOrders { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<PassportDatum> PassportData { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<PayRoll> PayRolls { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<PermissionExit> PermissionExits { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<PromotionJob> PromotionJobs { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<PromotionSalary> PromotionSalaries { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<SettlementEmp> SettlementEmps { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Skill> Skills { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<SocialnsuranceAmount> SocialnsuranceAmounts { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [InverseProperty("EmployeeCodeNavigation")]
        public virtual ICollection<Training> Training { get; set; }
    }
}