// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ErrorsLog")]
    public partial class ErrorsLog
    {
        [Key]
        public int ID { get; set; }
        public int InvoiceNo { get; set; }
        [StringLength(50)]
        public string ErrorDate { get; set; }
        [StringLength(50)]
        public string ErrorTime { get; set; }
        public int? BranchID { get; set; }
        [StringLength(100)]
        public string ComputerName { get; set; }
        [Column(TypeName = "ntext")]
        public string ErrorMessage { get; set; }
        public int? FrmValue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}