// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class EvaluationEmployee
    {
        public int PerID { get; set; }
        public int? EvaluationID { get; set; }
        public int? EmpDegree { get; set; }
        [StringLength(50)]
        public string PerDate { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string ManagerCode { get; set; }
        public int? InstallType { get; set; }
        [StringLength(250)]
        public string NotesDep { get; set; }
        [StringLength(250)]
        public string NotesManager { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}