// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ExpensesProduction")]
    public partial class ExpensesProduction
    {
        [Key]
        public int ID { get; set; }
        public int? CostNo { get; set; }
        public double? CostPerValue { get; set; }
        public double? CostAmount { get; set; }
        [Column(TypeName = "ntext")]
        public string CostNotes { get; set; }
        public int? InvoiceCode { get; set; }
        public int? BranchID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("BranchID")]
        [InverseProperty("ExpensesProductions")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("CostNo")]
        [InverseProperty("ExpensesProductions")]
        public virtual CostProduction CostNoNavigation { get; set; }
    }
}