// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class ExpensesPurchase_Sale
    {
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string AccIDExp { get; set; }
        public double? Amount { get; set; }
        public int? InvoiceID { get; set; }
        public int? BranchID { get; set; }
        public int? UserID { get; set; }
        public int? TypeExp { get; set; }
        public int? TypeFrm { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        public int? FinancialID { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public double? TaxRatio { get; set; }
        public double? TaxAmount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("ExpensesPurchase_SaleAccs")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("AccIDExp")]
        [InverseProperty("ExpensesPurchase_SaleAccIDExpNavigations")]
        public virtual TreeAccount AccIDExpNavigation { get; set; }
    }
}