// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("Experience")]
    public partial class Experience
    {
        [Key]
        public int ExperienceID { get; set; }
        public int EmployeeCode { get; set; }
        [StringLength(50)]
        public string StartDate { get; set; }
        [StringLength(50)]
        public string EndDate { get; set; }
        [StringLength(50)]
        public string WorkInCompany { get; set; }
        [StringLength(100)]
        public string CompanyName { get; set; }
        [StringLength(100)]
        public string ExitCompany { get; set; }
        public double? BasicSalary { get; set; }
        [StringLength(100)]
        public string JobDiscription { get; set; }
        public int? CityID { get; set; }
        public int? CountryID { get; set; }
        [StringLength(50)]
        public string DepartmentID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("Experiences")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}