// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("FinancialYear")]
    public partial class FinancialYear
    {
        public FinancialYear()
        {
            AccountBalanceDetails = new HashSet<AccountBalanceDetail>();
            AccountBalances = new HashSet<AccountBalance>();
            AllInvoices = new HashSet<AllInvoice>();
            AllVouchers = new HashSet<AllVoucher>();
            CostCenterBalances = new HashSet<CostCenterBalance>();
            InvoicePurchaseDetails = new HashSet<InvoicePurchaseDetail>();
            PagesNos = new HashSet<PagesNo>();
        }

        public int FID { get; set; }
        [Key]
        public int FinancialID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? BeginingFYGr { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EndingFYGr { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string BeginingFYHi { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string EndingFYHi { get; set; }
        [StringLength(100)]
        public string FinancialName { get; set; }
        public bool? Status { get; set; }
        public bool? Archive { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateFile { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [InverseProperty("Financial")]
        public virtual ICollection<AccountBalanceDetail> AccountBalanceDetails { get; set; }
        [InverseProperty("Financial")]
        public virtual ICollection<AccountBalance> AccountBalances { get; set; }
        [InverseProperty("Financial")]
        public virtual ICollection<AllInvoice> AllInvoices { get; set; }
        [InverseProperty("Financial")]
        public virtual ICollection<AllVoucher> AllVouchers { get; set; }
        [InverseProperty("Financial")]
        public virtual ICollection<CostCenterBalance> CostCenterBalances { get; set; }
        [InverseProperty("Financial")]
        public virtual ICollection<InvoicePurchaseDetail> InvoicePurchaseDetails { get; set; }
        [InverseProperty("Financial")]
        public virtual ICollection<PagesNo> PagesNos { get; set; }
    }
}