// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class FxiedAssetsDetail
    {
        [Key]
        public int ID { get; set; }
        public int AssetID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FromDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToDate { get; set; }
        public double? RateM { get; set; }
        public double? AccAmount { get; set; }
        public double? PerAmount { get; set; }
        public double? NewAmount { get; set; }
        public double? BookAmount { get; set; }
        public double? AddAmount { get; set; }
        public double? SubAmount { get; set; }
        public bool? Done { get; set; }
        public double? FexidAmount { get; set; }
        public int? FinancialID { get; set; }
        public int? AssetNo { get; set; }
        public double? SubAmountValue { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string FromDateHi { get; set; }
        [StringLength(50)]
        public string ToDateHi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AssetID")]
        [InverseProperty("FxiedAssetsDetails")]
        public virtual FxiedAsset Asset { get; set; }
    }
}