// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class FxiedAsset
    {
        public FxiedAsset()
        {
            FxiedAssetsAddeds = new HashSet<FxiedAssetsAdded>();
            FxiedAssetsDetails = new HashSet<FxiedAssetsDetail>();
        }

        public int ID { get; set; }
        [Key]
        public int AssetID { get; set; }
        public int? AssetCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(100)]
        public string ProviderName { get; set; }
        [StringLength(50)]
        public string AssetNo { get; set; }
        public double? PurchasePrice { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PurchaseDate { get; set; }
        [StringLength(50)]
        public string DatestrartDep { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        [StringLength(50)]
        public string Location { get; set; }
        public double? PerDep { get; set; }
        public int? DepType { get; set; }
        public int? GroupNo { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string AccExID { get; set; }
        [StringLength(50)]
        public string AccDeID { get; set; }
        public int? UserID { get; set; }
        public bool? Done { get; set; }
        public int? CostCenterID { get; set; }
        [StringLength(50)]
        public string AccCashID { get; set; }
        [StringLength(50)]
        public string AccProfitID { get; set; }
        public double? AmountRemove { get; set; }
        [StringLength(50)]
        public string DateRemove { get; set; }
        public int? AssetStats { get; set; }
        [Column(TypeName = "ntext")]
        public string NotesRemove { get; set; }
        [StringLength(50)]
        public string DatestrartDepHi { get; set; }
        [StringLength(50)]
        public string DateRemoveHi { get; set; }
        public int? DepTypeGaid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        public bool IsExecluded { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("FxiedAssetAccs")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("AccCashID")]
        [InverseProperty("FxiedAssetAccCashes")]
        public virtual TreeAccount AccCash { get; set; }
        [ForeignKey("AccDeID")]
        [InverseProperty("FxiedAssetAccDes")]
        public virtual TreeAccount AccDe { get; set; }
        [ForeignKey("AccExID")]
        [InverseProperty("FxiedAssetAccExes")]
        public virtual TreeAccount AccEx { get; set; }
        [ForeignKey("AccProfitID")]
        [InverseProperty("FxiedAssetAccProfits")]
        public virtual TreeAccount AccProfit { get; set; }
        [ForeignKey("BranchID")]
        [InverseProperty("FxiedAssets")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("GroupNo")]
        [InverseProperty("FxiedAssets")]
        public virtual MainDatum GroupNoNavigation { get; set; }
        [ForeignKey("UserID")]
        [InverseProperty("FxiedAssets")]
        public virtual AspNetUser User { get; set; }
        [InverseProperty("Asset")]
        public virtual ICollection<FxiedAssetsAdded> FxiedAssetsAddeds { get; set; }
        [InverseProperty("Asset")]
        public virtual ICollection<FxiedAssetsDetail> FxiedAssetsDetails { get; set; }
    }
}