// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class Holiday
    {
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string StartDate { get; set; }
        [StringLength(50)]
        public string EndDate { get; set; }
        public int? NoOfDays { get; set; }
        [StringLength(100)]
        public string LeName { get; set; }
        [StringLength(100)]
        public string LeNotes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}