// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class InvoicePurchaseDetail
    {
        [Key]
        public int ID { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? InvoiceCode { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountIn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("InvoicePurchaseDetails")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("FinancialID")]
        [InverseProperty("InvoicePurchaseDetails")]
        public virtual FinancialYear Financial { get; set; }
    }
}