// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("IPAddressDevice")]
    public partial class IPAddressDevice
    {
        public int ID { get; set; }
        [Key]
        public int BranchID { get; set; }
        [StringLength(100)]
        public string IPAddress { get; set; }
        public int? TerminalNo { get; set; }
        public bool? Status { get; set; }
        [StringLength(50)]
        public string UserNo { get; set; }
        [StringLength(50)]
        public string PassNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}