// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ItemRelatedAcc")]
    public partial class ItemRelatedAcc
    {
        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string fkItemID { get; set; }
        [Key]
        public int fkRelatedID { get; set; }
        [StringLength(50)]
        public string ItemAccID { get; set; }
        [StringLength(50)]
        public string DiscountAccID { get; set; }
        [StringLength(50)]
        public string SalesCostAccID { get; set; }
        [StringLength(50)]
        public string StoreAccID { get; set; }
        [StringLength(50)]
        public string VatAccID { get; set; }
        [Key]
        public int BranchID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }

        [ForeignKey("BranchID")]
        [InverseProperty("ItemRelatedAccs")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("DiscountAccID")]
        [InverseProperty("ItemRelatedAccDiscountAccs")]
        public virtual TreeAccount DiscountAcc { get; set; }
        [ForeignKey("ItemAccID")]
        [InverseProperty("ItemRelatedAccItemAccs")]
        public virtual TreeAccount ItemAcc { get; set; }
        [ForeignKey("SalesCostAccID")]
        [InverseProperty("ItemRelatedAccSalesCostAccs")]
        public virtual TreeAccount SalesCostAcc { get; set; }
        [ForeignKey("StoreAccID")]
        [InverseProperty("ItemRelatedAccStoreAccs")]
        public virtual TreeAccount StoreAcc { get; set; }
        [ForeignKey("VatAccID")]
        [InverseProperty("ItemRelatedAccVatAccs")]
        public virtual TreeAccount VatAcc { get; set; }
        [ForeignKey("fkItemID")]
        [InverseProperty("ItemRelatedAccs")]
        public virtual Item fkItem { get; set; }
    }
}