// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ItemsPersonality")]
    public partial class ItemsPersonality
    {
        [Key]
        public int ID { get; set; }
        public string ItemID { get; set; }
        public int? FirstAttributeID { get; set; }
        public int? SecondAttributeID { get; set; }
        public string Barcode { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
        public int? BranchID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }

        [ForeignKey("BranchID")]
        [InverseProperty("ItemsPersonalities")]
        public virtual BranchsAndWarehouse Branch { get; set; }
    }
}