// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class Item
    {
        public Item()
        {
            AllInvoiceJions = new HashSet<AllInvoiceJion>();
            AllInvoicesDetails = new HashSet<AllInvoicesDetail>();
            ItemRelatedAccs = new HashSet<ItemRelatedAcc>();
            ItemsAlternatives = new HashSet<ItemsAlternative>();
            ItemsJoinPOs = new HashSet<ItemsJoinPO>();
            ItemsJoins = new HashSet<ItemsJoin>();
            ItemsProductions = new HashSet<ItemsProduction>();
            PagesNos = new HashSet<PagesNo>();
            Quantities = new HashSet<Quantity>();
            QuantityBatches = new HashSet<QuantityBatch>();
            SalesmanQuantities = new HashSet<SalesmanQuantity>();
            UnitsItems = new HashSet<UnitsItem>();
        }

        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? MDCodeGroup { get; set; }
        public int? MDCodeUnit { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        [StringLength(50)]
        public string FactoryNo { get; set; }
        [Column(TypeName = "ntext")]
        public string OtherData { get; set; }
        [Column(TypeName = "ntext")]
        public string Barcode { get; set; }
        public int? BarcodeValue { get; set; }
        [Column(TypeName = "ntext")]
        public string Location { get; set; }
        public double? RequestQuantity { get; set; }
        public double? RequestPoint { get; set; }
        public int? ProfitSales { get; set; }
        public bool? ShowItemNoBar { get; set; }
        public bool? ShowItemNameBar { get; set; }
        public int? MDCodeGroup1 { get; set; }
        public int? MDCodeGroup2 { get; set; }
        public int? MDCodeGroup3 { get; set; }
        public int? MDCodeGroup4 { get; set; }
        public int? TypeItems { get; set; }
        public int? StatsItems { get; set; }
        [StringLength(100)]
        public string ItemNameEng { get; set; }
        public int? ProviderID { get; set; }
        [StringLength(50)]
        public string InsertItem { get; set; }
        public int? StatsTax { get; set; }
        public double? TaxValue { get; set; }
        public int? MDSalUnit { get; set; }
        public int? MDPurUnit { get; set; }
        public int? MDCodeSubGroup { get; set; }
        public int? QuatationUnit { get; set; }
        public int? OrderUnit { get; set; }
        public int? BookingUnit { get; set; }
        public int? ItemType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        public int? TypeStock { get; set; }
        public int? fkAternativeGroupID { get; set; }
        [StringLength(500)]
        public string Images { get; set; }
        public bool? IsDistributed { get; set; }

        [ForeignKey("BookingUnit")]
        [InverseProperty("ItemBookingUnitNavigations")]
        public virtual MainDatum BookingUnitNavigation { get; set; }
        [ForeignKey("ItemType")]
        [InverseProperty("ItemItemTypeNavigations")]
        public virtual MainDatum ItemTypeNavigation { get; set; }
        [ForeignKey("MDCodeGroup")]
        [InverseProperty("ItemMDCodeGroupNavigations")]
        public virtual MainDatum MDCodeGroupNavigation { get; set; }
        [ForeignKey("MDCodeSubGroup")]
        [InverseProperty("ItemMDCodeSubGroupNavigations")]
        public virtual MainDatum MDCodeSubGroupNavigation { get; set; }
        [ForeignKey("MDCodeUnit")]
        [InverseProperty("ItemMDCodeUnitNavigations")]
        public virtual MainDatum MDCodeUnitNavigation { get; set; }
        [ForeignKey("MDPurUnit")]
        [InverseProperty("ItemMDPurUnitNavigations")]
        public virtual MainDatum MDPurUnitNavigation { get; set; }
        [ForeignKey("MDSalUnit")]
        [InverseProperty("ItemMDSalUnitNavigations")]
        public virtual MainDatum MDSalUnitNavigation { get; set; }
        [ForeignKey("OrderUnit")]
        [InverseProperty("ItemOrderUnitNavigations")]
        public virtual MainDatum OrderUnitNavigation { get; set; }
        [ForeignKey("QuatationUnit")]
        [InverseProperty("ItemQuatationUnitNavigations")]
        public virtual MainDatum QuatationUnitNavigation { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<AllInvoiceJion> AllInvoiceJions { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<AllInvoicesDetail> AllInvoicesDetails { get; set; }
        [InverseProperty("fkItem")]
        public virtual ICollection<ItemRelatedAcc> ItemRelatedAccs { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<ItemsAlternative> ItemsAlternatives { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<ItemsJoinPO> ItemsJoinPOs { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<ItemsJoin> ItemsJoins { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<ItemsProduction> ItemsProductions { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<PagesNo> PagesNos { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<Quantity> Quantities { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<QuantityBatch> QuantityBatches { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<SalesmanQuantity> SalesmanQuantities { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<UnitsItem> UnitsItems { get; set; }
    }
}