// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("ItemsAlternative")]
    public partial class ItemsAlternative
    {
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        public int? BranchID { get; set; }
        public int? GroupID { get; set; }

        [ForeignKey("BranchID")]
        [InverseProperty("ItemsAlternatives")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("GroupID")]
        [InverseProperty("ItemsAlternatives")]
        public virtual MainDatum Group { get; set; }
        [ForeignKey("ItemID")]
        [InverseProperty("ItemsAlternatives")]
        public virtual Item Item { get; set; }
    }
}