// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("LeaveOrder")]
    public partial class LeaveOrder
    {
        public int ID { get; set; }
        [Key]
        public int LeaveOrderNo { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string LeaveOrderDate { get; set; }
        public int? TypeLeaveID { get; set; }
        [StringLength(50)]
        public string LeaveStart { get; set; }
        [StringLength(50)]
        public string LeaveEnd { get; set; }
        [StringLength(100)]
        public string LAddress { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        public bool? LeaveDone { get; set; }
        public double? CountDayLeave { get; set; }
        public bool? RetLeaveDone { get; set; }
        [StringLength(50)]
        public string ReDate { get; set; }
        public bool? ChPayment { get; set; }
        public int? TypePaymentID { get; set; }
        public double? Amount { get; set; }
        [StringLength(50)]
        public string DateAddPayment { get; set; }
        public double? CountDayLeaveWork { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("LeaveOrders")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}