// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class LkpTable
    {
        public int serial { get; set; }
        [Required]
        [StringLength(50)]
        public string sTableName { get; set; }
        [Key]
        [StringLength(50)]
        public string sTableNameAr { get; set; }
        [StringLength(50)]
        public string sTableNameEng { get; set; }
        [StringLength(50)]
        public string scode { get; set; }
        [StringLength(50)]
        public string ValueMember { get; set; }
        [StringLength(50)]
        public string DisplayMember { get; set; }
        [StringLength(50)]
        public string sfilter { get; set; }
        [StringLength(50)]
        public string BranchColName { get; set; }
    }
}