// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("MainDataDefault")]
    public partial class MainDataDefault
    {
        public int MDID { get; set; }
        [Key]
        public int MDDCode { get; set; }
        public int? MDDFrmValue { get; set; }
        public int? MDDValueNo { get; set; }
        [StringLength(50)]
        public string MDDName { get; set; }
        [StringLength(50)]
        public string MDDNameEng { get; set; }
        public bool? PostAuto { get; set; }
        public bool? AutoGaid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}