// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class MoveGaidDetail
    {
        [Key]
        public int ID { get; set; }
        public int? MovementID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(20)]
        public string DocNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        public string Details { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitLocal { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditLocal { get; set; }
        public int? GaneralType { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public int? CostCenterID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        public int? PCId { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("MoveGaidDetails")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("MovementID")]
        [InverseProperty("MoveGaidDetails")]
        public virtual MoveGaid Movement { get; set; }
    }
}