// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("MoveGaid")]
    public partial class MoveGaid
    {
        public MoveGaid()
        {
            MoveGaidDetails = new HashSet<MoveGaidDetail>();
        }

        public int MGID { get; set; }
        [Key]
        public int MoveID { get; set; }
        public int MoveCode { get; set; }
        public int? MoveSubCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string TimeGa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        public int? MoveGaidType { get; set; }
        public bool? Done { get; set; }
        public int? UserID { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitGaid { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditGaid { get; set; }
        public int? FinancialID { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public int? PrintCopyNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [InverseProperty("Movement")]
        public virtual ICollection<MoveGaidDetail> MoveGaidDetails { get; set; }
    }
}