// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("OhdaOrder")]
    public partial class OhdaOrder
    {
        public int ID { get; set; }
        [Key]
        public int OhdaOrderNo { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string OhdaOrderDate { get; set; }
        public int? TypeOhdaID { get; set; }
        public int? OhdaNo { get; set; }
        public double? OhdaAmount { get; set; }
        [StringLength(100)]
        public string Notes { get; set; }
        public bool? RetOhdaDone { get; set; }
        [StringLength(50)]
        public string ReDate { get; set; }
        public bool? Done { get; set; }
        [StringLength(50)]
        public string AccFundID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccFundID")]
        [InverseProperty("OhdaOrders")]
        public virtual TreeAccount AccFund { get; set; }
        [ForeignKey("EmployeeCode")]
        [InverseProperty("OhdaOrders")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}