// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("OpenBalanceJournal")]
    public partial class OpenBalanceJournal
    {
        public OpenBalanceJournal()
        {
            OpenBalanceJournalDetails = new HashSet<OpenBalanceJournalDetail>();
        }

        public int ID { get; set; }
        [Key]
        public int OpenBalID { get; set; }
        public int OpenBalCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string TimeGa { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        public bool? Done { get; set; }
        public int? UserID { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitOpenBal { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditOpenBal { get; set; }
        public int? FinancialID { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }

        [InverseProperty("OpenBal")]
        public virtual ICollection<OpenBalanceJournalDetail> OpenBalanceJournalDetails { get; set; }
    }
}