// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class OpenBalanceJournalDetail
    {
        [Key]
        public int ID { get; set; }
        public int? OpenBalID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        public string Details { get; set; }
        [Column(TypeName = "money")]
        public decimal? StartDebit { get; set; }
        [Column(TypeName = "money")]
        public decimal? StartCredit { get; set; }
        public int? GaneralType { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public int? CostCenterID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("OpenBalanceJournalDetails")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("OpenBalID")]
        [InverseProperty("OpenBalanceJournalDetails")]
        public virtual OpenBalanceJournal OpenBal { get; set; }
    }
}