// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("PagesNo")]
    public partial class PagesNo
    {
        public int PID { get; set; }
        [Key]
        public int PageNoID { get; set; }
        public int? PageNo { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? MDCode { get; set; }
        public int? WareHouseID { get; set; }
        public double? AvailableQuantity { get; set; }
        public double? InventoryQuantity { get; set; }
        [Column(TypeName = "ntext")]
        public string Location { get; set; }
        public int? InventoryID { get; set; }
        public int? FinancialID { get; set; }
        public double? QuantityFull { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpireDate { get; set; }
        [StringLength(150)]
        public string Batch { get; set; }
        [StringLength(150)]
        public string Personality { get; set; }

        [ForeignKey("FinancialID")]
        [InverseProperty("PagesNos")]
        public virtual FinancialYear Financial { get; set; }
        [ForeignKey("ItemID")]
        [InverseProperty("PagesNos")]
        public virtual Item Item { get; set; }
        [ForeignKey("MDCode")]
        [InverseProperty("PagesNos")]
        public virtual MainDatum MDCodeNavigation { get; set; }
    }
}