// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class PassportDatum
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string PassportNo { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string IssuPassportDate { get; set; }
        [StringLength(50)]
        public string IssuCountry { get; set; }
        [StringLength(100)]
        public string Notes { get; set; }
        public int? TypeID { get; set; }
        [StringLength(50)]
        public string StratNewDate { get; set; }
        [StringLength(50)]
        public string EndNewDate { get; set; }
        public int? Period { get; set; }
        [StringLength(50)]
        public string StratNewDateG { get; set; }
        [StringLength(50)]
        public string EndNewDateG { get; set; }
        public double? AmountVist { get; set; }
        public double? AmountRenwal { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("PassportData")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}