// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("PayRoll")]
    public partial class PayRoll
    {
        [Key]
        public int PayRollID { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string PayRollDate { get; set; }
        public double? BasicSalary { get; set; }
        public double? HousingAllow { get; set; }
        public double? TransAllow { get; set; }
        public double? BonusAmount { get; set; }
        public double? TotalOverTime { get; set; }
        public double? TotalDeduction { get; set; }
        public double? Loan { get; set; }
        public double? TotalPay { get; set; }
        public double? TotalOverTimeHours { get; set; }
        public double? TotalDeductionDay { get; set; }
        public int? PaymentType { get; set; }
        [StringLength(50)]
        public string CheckNo { get; set; }
        [StringLength(50)]
        public string CheckDate { get; set; }
        public int? BankID { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        public double? OtherAllow { get; set; }
        public double? HealthInsurance { get; set; }
        public double? AbesnAmount { get; set; }
        public bool? Done { get; set; }
        public int? PaySales { get; set; }
        public double? OpenBalance { get; set; }
        public double? Socialinsurance { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("PayRolls")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}