// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("PermissionExit")]
    public partial class PermissionExit
    {
        public int PermissionID { get; set; }
        [Key]
        [StringLength(50)]
        public string PermissionOrderNo { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string PermissionOrderDate { get; set; }
        [StringLength(50)]
        public string FromTime { get; set; }
        [StringLength(50)]
        public string ToTime { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        public int? PermissionType { get; set; }
        public int? NoMinutes { get; set; }
        public bool? PermissionDone { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("PermissionExits")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}