// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("PromotionJob")]
    public partial class PromotionJob
    {
        [Key]
        public int ID { get; set; }
        public int? OrderNo { get; set; }
        public int? EmployeeCode { get; set; }
        [StringLength(50)]
        public string OrderDate { get; set; }
        public int? DepartmentID { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        public int? CategoryID { get; set; }
        public int? JobID { get; set; }
        public int? IDJobOld { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("PromotionJobs")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}