// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("PromotionSalary")]
    public partial class PromotionSalary
    {
        public int ID { get; set; }
        public int EmployeeCode { get; set; }
        [Key]
        public int OrderNo { get; set; }
        [StringLength(50)]
        public string OrderDate { get; set; }
        public int? WorkingDays { get; set; }
        public int? WorkingHours { get; set; }
        public int? NoOfVacationDay { get; set; }
        public int? NoOfTicket { get; set; }
        /// <summary>
        /// 1=Monthly, 2=quartyear, 3=Halfyear
        /// </summary>
        public int? PayType { get; set; }
        public double? BasicSalary { get; set; }
        public double? HousingAllow { get; set; }
        public double? TransAllow { get; set; }
        public double? HealthInsurance { get; set; }
        public double? OtherAllow { get; set; }
        public double? TicketAmount { get; set; }
        public double? Net { get; set; }
        public int? ContractNo { get; set; }
        public double? SocialnsuranceAmount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("PromotionSalaries")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}