// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("Quantity")]
    public partial class Quantity
    {
        public int QuantityCode { get; set; }
        [Key]
        public int WareHouseID { get; set; }
        [Key]
        [StringLength(50)]
        public string ItemID { get; set; }
        [Key]
        public int BranchID { get; set; }
        public double? QuantityAv { get; set; }
        public double? QuantityIn { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpireDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("BranchID")]
        [InverseProperty("QuantityBranches")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("ItemID")]
        [InverseProperty("Quantities")]
        public virtual Item Item { get; set; }
        [ForeignKey("WareHouseID")]
        [InverseProperty("QuantityWareHouses")]
        public virtual BranchsAndWarehouse WareHouse { get; set; }
    }
}