// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class Reconciliation
    {
        public int RecID { get; set; }
        [Key]
        public int RecCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        public int? TypeCompare { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? UserID { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        [StringLength(50)]
        public string FromDate { get; set; }
        [StringLength(50)]
        public string ToDate { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("Reconciliations")]
        public virtual TreeAccount Acc { get; set; }
    }
}