// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("SalesmanQuantity")]
    public partial class SalesmanQuantity
    {
        [Key]
        public int ID { get; set; }
        public int? BranchID { get; set; }
        public int? SalesmanID { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        public double? Quantity { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("BranchID")]
        [InverseProperty("SalesmanQuantities")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("ItemID")]
        [InverseProperty("SalesmanQuantities")]
        public virtual Item Item { get; set; }
        [ForeignKey("SalesmanID")]
        [InverseProperty("SalesmanQuantities")]
        public virtual SalesManInfo Salesman { get; set; }
    }
}