// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("SalesManInfo")]
    public partial class SalesManInfo
    {
        public SalesManInfo()
        {
            AllInvoices = new HashSet<AllInvoice>();
            AllVouchers = new HashSet<AllVoucher>();
            ProviderCustomers = new HashSet<ProviderCustomer>();
            SalesmanQuantities = new HashSet<SalesmanQuantity>();
        }

        public int SalesManID { get; set; }
        [Key]
        public int SalesManCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(100)]
        public string SalName { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? TargetIncomeRequired { get; set; }
        public int? TargetSalesMonthly { get; set; }
        public int? CommissionType { get; set; }
        public int? CommissionValue { get; set; }
        public bool? CommissionOthers { get; set; }
        public int? CommissionOthersValue { get; set; }
        public int? HisWarhouse { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(100)]
        public string SalNameEng { get; set; }
        public int? Fund { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("AccID")]
        [InverseProperty("SalesManInfos")]
        public virtual TreeAccount Acc { get; set; }
        [ForeignKey("BranchID")]
        [InverseProperty("SalesManInfos")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [InverseProperty("SalesManCodeNavigation")]
        public virtual ICollection<AllInvoice> AllInvoices { get; set; }
        [InverseProperty("SalesManCodeNavigation")]
        public virtual ICollection<AllVoucher> AllVouchers { get; set; }
        [InverseProperty("Saleman")]
        public virtual ICollection<ProviderCustomer> ProviderCustomers { get; set; }
        [InverseProperty("Salesman")]
        public virtual ICollection<SalesmanQuantity> SalesmanQuantities { get; set; }
    }
}