// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("SettingBarcode")]
    public partial class SettingBarcode
    {
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string RotItems { get; set; }
        public int? Alignment { get; set; }
        public int? LabLocation { get; set; }
        public bool? ShowItemsNo { get; set; }
        public bool? ShowItemName { get; set; }
        public bool? ShowText { get; set; }
        public bool? ShowPrice { get; set; }
        public double? SizeH { get; set; }
        public double? SizeW { get; set; }
        [StringLength(50)]
        public string Des { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}