// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("SettingSystemHR")]
    public partial class SettingSystemHR
    {
        [Key]
        public int ID { get; set; }
        public bool? CeateBackupExitP { get; set; }
        public bool? CreateBackupFDay { get; set; }
        [StringLength(200)]
        public string BackupPath { get; set; }
        public int? TypeCalendarNo { get; set; }
        public int? TybeLangeugeNo { get; set; }
        [StringLength(50)]
        public string CurrencyName { get; set; }
        [StringLength(50)]
        public string CurrencyPart { get; set; }
        [StringLength(50)]
        public string CurrencyCode { get; set; }
        public bool? ShowIcons { get; set; }
        public bool? AramConCh { get; set; }
        public int? AramConDay { get; set; }
        public int? BranchID { get; set; }
        public bool? AramLeaveCh { get; set; }
        public int? AramLeaveDay { get; set; }
        public bool? AramPossPortCh { get; set; }
        public int? AramPossPortDay { get; set; }
        public bool? AramDocumentCh { get; set; }
        public int? AramDocumentDay { get; set; }
        public int? LeaveYears { get; set; }
        public int? LeaveDays { get; set; }
        public int? BounsYears { get; set; }
        public int? BounsDays { get; set; }
        public int? ChkBouns { get; set; }
        public int? ShowSetup { get; set; }
        public int? AramDocumentOhda { get; set; }
        public bool? AramOhdCh { get; set; }
        [StringLength(200)]
        public string BackupPathDoc { get; set; }
        public int? ChOverTime { get; set; }
        public int? ChAbsent { get; set; }
        public int? LeaveFiveYear { get; set; }
        public int? BounsFiveYear { get; set; }
        public double? PerCom1 { get; set; }
        public double? PerEmp1 { get; set; }
        public double? PerCom2 { get; set; }
        public double? PerEmp2 { get; set; }
        public bool? PrintNameC { get; set; }
        public double? OpenPeriodOne { get; set; }
        public double? ClosePeriodOne { get; set; }
        public double? OpenPeriodTwo { get; set; }
        public double? ClosePeriodTwo { get; set; }
        public int? ChTypeAtt { get; set; }
        [StringLength(50)]
        public string StatTime { get; set; }
        [StringLength(50)]
        public string EndTime { get; set; }
        [StringLength(50)]
        public string Att1 { get; set; }
        [StringLength(50)]
        public string Att2 { get; set; }
        [StringLength(50)]
        public string Exit1 { get; set; }
        [StringLength(50)]
        public string Exit2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}