// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class Sponsor
    {
        public int SID { get; set; }
        [Key]
        [StringLength(50)]
        public string SNo { get; set; }
        [StringLength(100)]
        public string SName { get; set; }
        [StringLength(50)]
        public string SPhone { get; set; }
        [StringLength(50)]
        public string SFax { get; set; }
        [StringLength(250)]
        public string SAddress { get; set; }
        public int? SType { get; set; }
        [StringLength(50)]
        public string RNo { get; set; }
        [StringLength(50)]
        public string RNo1 { get; set; }
        [StringLength(50)]
        public string IussR { get; set; }
        [StringLength(50)]
        public string IussR1 { get; set; }
        [StringLength(50)]
        public string DateIuss { get; set; }
        [StringLength(50)]
        public string DateIuss1 { get; set; }
        [StringLength(50)]
        public string DateExpired { get; set; }
        [StringLength(50)]
        public string DateExpired1 { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}