// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("SubModule")]
    public partial class SubModule
    {
        public SubModule()
        {
            RoleModulePermissions = new HashSet<RoleModulePermission>();
        }

        public int Id { get; set; }
        [Key]
        [StringLength(10)]
        public string SubModuleID { get; set; }
        [Required]
        [StringLength(50)]
        public string NameAr { get; set; }
        [StringLength(50)]
        public string NameEn { get; set; }
        [Required]
        [StringLength(50)]
        public string ModuleID { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("ModuleID")]
        [InverseProperty("SubModules")]
        public virtual Module Module { get; set; }
        [InverseProperty("SubModule")]
        public virtual ICollection<RoleModulePermission> RoleModulePermissions { get; set; }
    }
}