// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("Synchronization")]
    public partial class Synchronization
    {
        [Key]
        public int ID { get; set; }
        [StringLength(100)]
        public string NameServerM { get; set; }
        [StringLength(100)]
        public string PasswordSeM { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        [StringLength(100)]
        public string LoginNameM { get; set; }
        public int? Manual { get; set; }
        [StringLength(100)]
        public string NameServerPc { get; set; }
        [StringLength(100)]
        public string PasswordSePc { get; set; }
        [StringLength(100)]
        public string LoginNamePc { get; set; }
        public int? SyncKind { get; set; }
        [StringLength(200)]
        public string WebSyncUrl { get; set; }
        [StringLength(50)]
        public string WebSyncUrl_Login { get; set; }
        [StringLength(50)]
        public string WebSyncUrl_Password { get; set; }
        [StringLength(200)]
        public string AltSnapshotFolder_Path { get; set; }
        [StringLength(50)]
        public string AltSnapshotFolder_User { get; set; }
        [StringLength(50)]
        public string AltSnapshotFolder_Password { get; set; }
        public int? RepEvrey { get; set; }
        public int? BranchID { get; set; }
        public int? TimeSync { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}