// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class Training
    {
        [Key]
        public int TrainID { get; set; }
        public int EmployeeCode { get; set; }
        [StringLength(50)]
        public string StartDate { get; set; }
        [StringLength(50)]
        public string EndDate { get; set; }
        [StringLength(50)]
        public string WorkInCompany { get; set; }
        [StringLength(100)]
        public string TrainName { get; set; }
        [StringLength(100)]
        public string TrainDiscription { get; set; }
        public int? CityID { get; set; }
        public int? CountryID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("EmployeeCode")]
        [InverseProperty("Training")]
        public virtual EmployeesDetail EmployeeCodeNavigation { get; set; }
    }
}