// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("TreeAccountDefualt")]
    public partial class TreeAccountDefualt
    {
        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string AccName { get; set; }
        public int? MainFinalAccount { get; set; }
        [Column(TypeName = "money")]
        public decimal? MaxBalance { get; set; }
        [StringLength(50)]
        public string MainAccountNo { get; set; }
        [StringLength(50)]
        public string AccPeriod { get; set; }
        public int? MainOrSub { get; set; }
        public int? LevelAccount { get; set; }
        public bool? JoinCostCenter { get; set; }
        [StringLength(50)]
        public string AccNameEng { get; set; }
        [StringLength(50)]
        public string TaxNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
    }
}