// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Table("TreeAccount")]
    public partial class TreeAccount
    {
        public TreeAccount()
        {
            AccountBalanceDetails = new HashSet<AccountBalanceDetail>();
            AccountBalances = new HashSet<AccountBalance>();
            AllInvoices = new HashSet<AllInvoice>();
            AllVouchers = new HashSet<AllVoucher>();
            AllVouchersDetails = new HashSet<AllVouchersDetail>();
            BonusOrders = new HashSet<BonusOrder>();
            BranchsAndWarehouses = new HashSet<BranchsAndWarehouse>();
            ComissionBanks = new HashSet<ComissionBank>();
            CostProductions = new HashSet<CostProduction>();
            CustomersBranches = new HashSet<CustomersBranch>();
            DistributionExpenses = new HashSet<DistributionExpense>();
            EmployeesDetailAccIDDeNavigations = new HashSet<EmployeesDetail>();
            EmployeesDetailAccIDENavigations = new HashSet<EmployeesDetail>();
            EmployeesDetailAccIDLNavigations = new HashSet<EmployeesDetail>();
            EmployeesDetailAccIDONavigations = new HashSet<EmployeesDetail>();
            ExpensesPurchase_SaleAccIDExpNavigations = new HashSet<ExpensesPurchase_Sale>();
            ExpensesPurchase_SaleAccs = new HashSet<ExpensesPurchase_Sale>();
            FxiedAssetAccCashes = new HashSet<FxiedAsset>();
            FxiedAssetAccDes = new HashSet<FxiedAsset>();
            FxiedAssetAccExes = new HashSet<FxiedAsset>();
            FxiedAssetAccProfits = new HashSet<FxiedAsset>();
            FxiedAssetAccs = new HashSet<FxiedAsset>();
            InvoicePurchaseDetails = new HashSet<InvoicePurchaseDetail>();
            ItemRelatedAccDiscountAccs = new HashSet<ItemRelatedAcc>();
            ItemRelatedAccItemAccs = new HashSet<ItemRelatedAcc>();
            ItemRelatedAccSalesCostAccs = new HashSet<ItemRelatedAcc>();
            ItemRelatedAccStoreAccs = new HashSet<ItemRelatedAcc>();
            ItemRelatedAccVatAccs = new HashSet<ItemRelatedAcc>();
            Loans = new HashSet<Loan>();
            MainAccCompanies = new HashSet<MainAccCompany>();
            MainAccCompanyHRs = new HashSet<MainAccCompanyHR>();
            MainData = new HashSet<MainDatum>();
            MoveGaidDetails = new HashSet<MoveGaidDetail>();
            OhdaOrders = new HashSet<OhdaOrder>();
            OpenBalanceJournalDetails = new HashSet<OpenBalanceJournalDetail>();
            OverTimeOrders = new HashSet<OverTimeOrder>();
            ProviderCustomers = new HashSet<ProviderCustomer>();
            Reconciliations = new HashSet<Reconciliation>();
            SalesManInfos = new HashSet<SalesManInfo>();
            TrialBals = new HashSet<TrialBal>();
        }

        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(100)]
        public string AccName { get; set; }
        public int? MainFinalAccount { get; set; }
        [Column(TypeName = "money")]
        public decimal? MaxBalance { get; set; }
        [StringLength(50)]
        public string MainAccountNo { get; set; }
        [StringLength(50)]
        public string AccPeriod { get; set; }
        public int? MainOrSub { get; set; }
        public int? LevelAccount { get; set; }
        public bool? JoinCostCenter { get; set; }
        [StringLength(50)]
        public string AccNameEng { get; set; }
        [StringLength(50)]
        public string TaxNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [InverseProperty("Acc")]
        public virtual ICollection<AccountBalanceDetail> AccountBalanceDetails { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<AccountBalance> AccountBalances { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<AllInvoice> AllInvoices { get; set; }
        [InverseProperty("FromAcc")]
        public virtual ICollection<AllVoucher> AllVouchers { get; set; }
        [InverseProperty("ToAcc")]
        public virtual ICollection<AllVouchersDetail> AllVouchersDetails { get; set; }
        [InverseProperty("AccFund")]
        public virtual ICollection<BonusOrder> BonusOrders { get; set; }
        [InverseProperty("BWAcc")]
        public virtual ICollection<BranchsAndWarehouse> BranchsAndWarehouses { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<ComissionBank> ComissionBanks { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<CostProduction> CostProductions { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<CustomersBranch> CustomersBranches { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<DistributionExpense> DistributionExpenses { get; set; }
        [InverseProperty("AccIDDeNavigation")]
        public virtual ICollection<EmployeesDetail> EmployeesDetailAccIDDeNavigations { get; set; }
        [InverseProperty("AccIDENavigation")]
        public virtual ICollection<EmployeesDetail> EmployeesDetailAccIDENavigations { get; set; }
        [InverseProperty("AccIDLNavigation")]
        public virtual ICollection<EmployeesDetail> EmployeesDetailAccIDLNavigations { get; set; }
        [InverseProperty("AccIDONavigation")]
        public virtual ICollection<EmployeesDetail> EmployeesDetailAccIDONavigations { get; set; }
        [InverseProperty("AccIDExpNavigation")]
        public virtual ICollection<ExpensesPurchase_Sale> ExpensesPurchase_SaleAccIDExpNavigations { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<ExpensesPurchase_Sale> ExpensesPurchase_SaleAccs { get; set; }
        [InverseProperty("AccCash")]
        public virtual ICollection<FxiedAsset> FxiedAssetAccCashes { get; set; }
        [InverseProperty("AccDe")]
        public virtual ICollection<FxiedAsset> FxiedAssetAccDes { get; set; }
        [InverseProperty("AccEx")]
        public virtual ICollection<FxiedAsset> FxiedAssetAccExes { get; set; }
        [InverseProperty("AccProfit")]
        public virtual ICollection<FxiedAsset> FxiedAssetAccProfits { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<FxiedAsset> FxiedAssetAccs { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<InvoicePurchaseDetail> InvoicePurchaseDetails { get; set; }
        [InverseProperty("DiscountAcc")]
        public virtual ICollection<ItemRelatedAcc> ItemRelatedAccDiscountAccs { get; set; }
        [InverseProperty("ItemAcc")]
        public virtual ICollection<ItemRelatedAcc> ItemRelatedAccItemAccs { get; set; }
        [InverseProperty("SalesCostAcc")]
        public virtual ICollection<ItemRelatedAcc> ItemRelatedAccSalesCostAccs { get; set; }
        [InverseProperty("StoreAcc")]
        public virtual ICollection<ItemRelatedAcc> ItemRelatedAccStoreAccs { get; set; }
        [InverseProperty("VatAcc")]
        public virtual ICollection<ItemRelatedAcc> ItemRelatedAccVatAccs { get; set; }
        [InverseProperty("AccFund")]
        public virtual ICollection<Loan> Loans { get; set; }
        [InverseProperty("Account")]
        public virtual ICollection<MainAccCompany> MainAccCompanies { get; set; }
        [InverseProperty("Account")]
        public virtual ICollection<MainAccCompanyHR> MainAccCompanyHRs { get; set; }
        [InverseProperty("MAcc")]
        public virtual ICollection<MainDatum> MainData { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<MoveGaidDetail> MoveGaidDetails { get; set; }
        [InverseProperty("AccFund")]
        public virtual ICollection<OhdaOrder> OhdaOrders { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<OpenBalanceJournalDetail> OpenBalanceJournalDetails { get; set; }
        [InverseProperty("AccFund")]
        public virtual ICollection<OverTimeOrder> OverTimeOrders { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<ProviderCustomer> ProviderCustomers { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<Reconciliation> Reconciliations { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<SalesManInfo> SalesManInfos { get; set; }
        [InverseProperty("Acc")]
        public virtual ICollection<TrialBal> TrialBals { get; set; }
    }
}