// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    public partial class UnitsItem
    {
        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        public string ItemID { get; set; }
        [Key]
        public int UnitID { get; set; }
        [Key]
        public int BranchID { get; set; }
        public double? Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitSalesPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitMinSalesPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitWholePrice { get; set; }
        [StringLength(50)]
        public string UnitBarcode { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceCost { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceAverage { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceCostOpen { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceMarket { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceSalesman { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceAfterTax { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("ItemID")]
        [InverseProperty("UnitsItems")]
        public virtual Item Item { get; set; }
        [ForeignKey("UnitID")]
        [InverseProperty("UnitsItems")]
        public virtual MainDatum Unit { get; set; }
    }
}