// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    [Table("UserDataPermissionHR")]
    public partial class UserDataPermissionHR
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int BranchID { get; set; }
        [Column(TypeName = "ntext")]
        public string PermssisonString { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }

        [ForeignKey("BranchID")]
        public virtual BranchsAndWarehouse Branch { get; set; }
        [ForeignKey("UserID")]
        public virtual UsersDatum User { get; set; }
    }
}