// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewSkill
    {
        [StringLength(50)]
        public string SkillLevelNameA { get; set; }
        [StringLength(50)]
        public string LastUsed { get; set; }
        [StringLength(50)]
        public string YearsOfExperience { get; set; }
        public int? SkillLevelID { get; set; }
        [StringLength(100)]
        public string Skill { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        public int SkillID { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(50)]
        public string SkillLevelNameE { get; set; }
    }
}