// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewExperience
    {
        public int ExperienceID { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string StartDate { get; set; }
        [StringLength(50)]
        public string EndDate { get; set; }
        [StringLength(50)]
        public string WorkInCompany { get; set; }
        [StringLength(100)]
        public string CompanyName { get; set; }
        [StringLength(100)]
        public string ExitCompany { get; set; }
        public double? BasicSalary { get; set; }
        [StringLength(100)]
        public string JobDiscription { get; set; }
        public int? CityID { get; set; }
        public int? CountryID { get; set; }
        [StringLength(50)]
        public string DepartmentID { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
    }
}