// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewAllVoucher
    {
        public int VoucherID { get; set; }
        public int VoucherCode { get; set; }
        public int? BranchID { get; set; }
        public int? UserID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        [StringLength(50)]
        public string FromAccID { get; set; }
        [Column(TypeName = "ntext")]
        public string VoucherDetails { get; set; }
        public bool? Done { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "money")]
        public decimal? VoucherTotal { get; set; }
        [StringLength(100)]
        public string AccName { get; set; }
        public int? FrmValueVoucher { get; set; }
        public int FrmValue { get; set; }
        public int? SalesManCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateVoucher { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        [StringLength(100)]
        public string ToAccName { get; set; }
        [StringLength(50)]
        public string ToAccID { get; set; }
        [StringLength(100)]
        public string CostCenterName { get; set; }
        [Column(TypeName = "money")]
        public decimal Total { get; set; }
    }
}