// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewOverTime
    {
        public int OverTimeID { get; set; }
        [Required]
        [StringLength(50)]
        public string OverTimeOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string OverTimeOrderDate { get; set; }
        public double? TotalOverHourse { get; set; }
        [Column(TypeName = "money")]
        public decimal? OverTimeAmount { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        [StringLength(50)]
        public string AddOverDate { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
    }
}