// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewSettlement
    {
        public int SettID { get; set; }
        [StringLength(50)]
        public string SettDate { get; set; }
        public double? BasicSalary { get; set; }
        public double? HousingAllow { get; set; }
        public double? TransAllow { get; set; }
        public double? BonusAmount { get; set; }
        public double? TotalOverTime { get; set; }
        public double? TotalDeduction { get; set; }
        public double? Loan { get; set; }
        public double? TotalPay { get; set; }
        public double? TotalOverTimeHours { get; set; }
        public double? TotalDeductionDay { get; set; }
        public int? PaymentType { get; set; }
        [StringLength(50)]
        public string CheckNo { get; set; }
        [StringLength(50)]
        public string CheckDate { get; set; }
        public int? BankID { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        public double? OtherAllow { get; set; }
        public double? HealthInsurance { get; set; }
        public double? AbesnAmount { get; set; }
        public bool? Done { get; set; }
        public double? DayNoRemain { get; set; }
        public double? DayNoLe { get; set; }
        public double? HospAmount { get; set; }
        public double? TickAmount { get; set; }
        public double? SetLeveAmount { get; set; }
        public double? SetAmount { get; set; }
        public double? OpenBalance { get; set; }
        public double? DayS { get; set; }
        [StringLength(50)]
        public string MDDName { get; set; }
        [StringLength(50)]
        public string MDDNameEng { get; set; }
        [Column(TypeName = "ntext")]
        public string PeriodNote { get; set; }
        public double? DaysSett { get; set; }
        [StringLength(50)]
        public string DateStartSett { get; set; }
        public double? DaysLeave { get; set; }
        [StringLength(50)]
        public string DateStartLeave { get; set; }
        public int SettNo { get; set; }
        public int? TypeSett { get; set; }
        public double? AmountOther { get; set; }
        public double? Socialinsurance { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(100)]
        public string DepartmentNameA { get; set; }
        [StringLength(100)]
        public string DepartmentNameE { get; set; }
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        public int Active { get; set; }
        [StringLength(50)]
        public string NameProfessionsE { get; set; }
        [StringLength(50)]
        public string NameProfessionsA { get; set; }
        [StringLength(100)]
        public string JobNameE { get; set; }
        [StringLength(100)]
        public string JobNameA { get; set; }
        [StringLength(100)]
        public string MaritalStatusNameE { get; set; }
        [StringLength(100)]
        public string MaritalStatusNameA { get; set; }
        [StringLength(100)]
        public string QualificationNameA { get; set; }
        [StringLength(100)]
        public string QualificationNameE { get; set; }
        [StringLength(30)]
        public string CConNameArb { get; set; }
        [StringLength(30)]
        public string CConNameEng { get; set; }
        [StringLength(50)]
        public string StTypeNameE { get; set; }
        [StringLength(50)]
        public string StTypeNameA { get; set; }
        [StringLength(100)]
        public string ReligionNameA { get; set; }
        [StringLength(100)]
        public string ReligionNameE { get; set; }
        public int? Status { get; set; }
        [StringLength(50)]
        public string HireDate { get; set; }
        [StringLength(50)]
        public string BankAccountNo { get; set; }
        [StringLength(50)]
        public string BankName { get; set; }
        public int? GenderID { get; set; }
        [StringLength(50)]
        public string DOBHI { get; set; }
        [StringLength(50)]
        public string DOBGR { get; set; }
        [StringLength(100)]
        public string SponsorNameID { get; set; }
        public int? SType { get; set; }
        [StringLength(50)]
        public string AccIDO { get; set; }
        [StringLength(50)]
        public string AccIDE { get; set; }
        [StringLength(50)]
        public string AccIDDe { get; set; }
        [Column(TypeName = "image")]
        public byte[] EmpImage { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string GenderA { get; set; }
        [StringLength(50)]
        public string GenderE { get; set; }
        [StringLength(100)]
        public string SName { get; set; }
        [StringLength(50)]
        public string SPhone { get; set; }
        [StringLength(50)]
        public string SFax { get; set; }
        public int? Nationality { get; set; }
        [StringLength(250)]
        public string SAddress { get; set; }
        public int? BWCode { get; set; }
        public int? ProfessionsID { get; set; }
        public int? BloodType { get; set; }
        [StringLength(50)]
        public string BloodTypeName { get; set; }
        [StringLength(100)]
        public string JobDescription { get; set; }
        [Column(TypeName = "ntext")]
        public string PermissionString { get; set; }
        [StringLength(50)]
        public string JobID { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        public int? DepartmentID { get; set; }
        public int? CategoryID { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        [StringLength(50)]
        public string AccIDL { get; set; }
    }
}