// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewBalanceCostCenter
    {
        [Required]
        [StringLength(50)]
        public string AccNo { get; set; }
        [StringLength(50)]
        public string AccName { get; set; }
        public int OpenB { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
        public int Bal { get; set; }
    }
}