// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewVAT
    {
        public int? InvoiceCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        [StringLength(50)]
        public string TaxNo { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        [StringLength(63)]
        public string InvoiceType { get; set; }
        public string PCName { get; set; }
        public double? total { get; set; }
        [Column(TypeName = "numeric(19, 4)")]
        public decimal? DiscountInv { get; set; }
        [Column(TypeName = "numeric(19, 4)")]
        public decimal? CigaretTax { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? TaxAmount { get; set; }
        public string Note { get; set; }
        [StringLength(100)]
        public string CostCenter { get; set; }
        public int? Done { get; set; }
        public int? FinancialID { get; set; }
        public int? FrmValue { get; set; }
        public int? BranchID { get; set; }
        [StringLength(100)]
        public string AccID { get; set; }
        public int? StatsTax { get; set; }
    }
}