// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewOpenBalanceJournal
    {
        [StringLength(100)]
        public string AccName { get; set; }
        public int? LevelAccount { get; set; }
        public int? MDDFrmValue { get; set; }
        [StringLength(50)]
        public string TypeNameGaid { get; set; }
        public int? ID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string DateGrD { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public string Details { get; set; }
        [Column(TypeName = "money")]
        public decimal? StartDebit { get; set; }
        [Column(TypeName = "money")]
        public decimal? StartCredit { get; set; }
        public int? GaneralType { get; set; }
        public int? CostCenterID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModified { get; set; }
        [StringLength(100)]
        public string CostCenterName { get; set; }
        public int? MFrmValue { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        public int OpenBalID { get; set; }
        public int OpenBalCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string TimeGa { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        public bool? Done { get; set; }
        public int? UserID { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitOpenBal { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditOpenBal { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Expr2 { get; set; }
        [Required]
        [StringLength(50)]
        public string Expr3 { get; set; }
        [Required]
        [StringLength(50)]
        public string Expr4 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Expr5 { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [Column(TypeName = "money")]
        public decimal? Amount { get; set; }
    }
}