// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewDeducation
    {
        public int? DeductionType { get; set; }
        [StringLength(50)]
        public string DeductionTypeNameE { get; set; }
        [StringLength(50)]
        public string DeductionTypeNameA { get; set; }
        [Required]
        [StringLength(50)]
        public string DeductionOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string DeductionOrderDate { get; set; }
        [Column(TypeName = "money")]
        public decimal? DeductionAmount { get; set; }
        [StringLength(50)]
        public string Note { get; set; }
        [StringLength(50)]
        public string DeductionForDate { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
    }
}