// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewPromotionSalary
    {
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        public int OrderNo { get; set; }
        [StringLength(50)]
        public string OrderDate { get; set; }
        public int? WorkingDays { get; set; }
        public int? WorkingHours { get; set; }
        public int? NoOfVacationDay { get; set; }
        public int? NoOfTicket { get; set; }
        public int? PayType { get; set; }
        public double? BasicSalary { get; set; }
        public double? HousingAllow { get; set; }
        public double? TransAllow { get; set; }
        public double? HealthInsurance { get; set; }
        public double? OtherAllow { get; set; }
        public double? TicketAmount { get; set; }
        public double? Net { get; set; }
        public int? ContractNo { get; set; }
        [StringLength(50)]
        public string ContractStart { get; set; }
        [StringLength(50)]
        public string ContractEnd { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        public double? SocialnsuranceAmount { get; set; }
    }
}