// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewLanguage
    {
        [StringLength(50)]
        public string LangLastUsed { get; set; }
        public double? LangYearsOfExperience { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        public int SkillLevelID { get; set; }
        [StringLength(50)]
        public string SkillLevelNameE { get; set; }
        [StringLength(50)]
        public string SkillLevelNameA { get; set; }
        [StringLength(50)]
        public string LanguageNameA { get; set; }
        [StringLength(50)]
        public string LanguageNameE { get; set; }
        public int EmpLangID { get; set; }
        public int? LanguageID { get; set; }
        public int? LangSkillLevelID { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
    }
}