// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewMovementsEntry
    {
        public int? BranchID { get; set; }
        public int MoveCode { get; set; }
        public int? MoveSubCode { get; set; }
        public int MoveID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        public int? MoveGaidType { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitGaid { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditGaid { get; set; }
        public int? FinancialID { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        [StringLength(20)]
        public string DocNo { get; set; }
        public string Details { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitLocal { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditLocal { get; set; }
        public int? GaneralType { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(100)]
        public string AccName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGrD { get; set; }
        [Column(TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(50)]
        public string TimeGa { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        public int? MDDFrmValue { get; set; }
        [StringLength(50)]
        public string TypeNameGaid { get; set; }
        public int? LevelAccount { get; set; }
        public bool? Done { get; set; }
        public int? CostCenterID { get; set; }
        [StringLength(100)]
        public string CostCenter { get; set; }
        public int? MFrmValue { get; set; }
        public int? UserID { get; set; }
        public int? ID { get; set; }
        public int? PCId { get; set; }
    }
}