// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewProfitItem
    {
        public int? InvoiceID { get; set; }
        public int? BranchID { get; set; }
        public int? FinancialID { get; set; }
        public int? PrCuID { get; set; }
        public int? FrmValue { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? UnitID { get; set; }
        public double? QuantityFull { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? CostPrice { get; set; }
        public double? Quantity { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        public int? SalesManCode { get; set; }
        public int? PayType { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        public int? UserID { get; set; }
        public int? CashierID { get; set; }
        [Column(TypeName = "money")]
        public decimal? OtherPrice { get; set; }
        public int? MDCodeGroup { get; set; }
        public int? MDCodeUnit { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        public int? MDCodeGroup1 { get; set; }
        public int? MDCodeGroup2 { get; set; }
        public int? MDCodeGroup3 { get; set; }
        public int? MDCodeGroup4 { get; set; }
        public int? TypeItems { get; set; }
        public int? StatsItems { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [StringLength(100)]
        public string PCName { get; set; }
        public double? NetQuantity { get; set; }
        public double? NetTotal { get; set; }
        public double? NetCostPriceTotal { get; set; }
        public double? Profit { get; set; }
        public double? NetOtherPriceTotal { get; set; }
        public double? ProfitSalesman { get; set; }
        public int? ReturnInvoiceID { get; set; }
        public int? UpdatePrice { get; set; }
        public int? WarehouseID { get; set; }
        [StringLength(50)]
        public string TimeIN { get; set; }
        public int? MDCodeSubGroup { get; set; }
    }
}