// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewDebitOrCredit
    {
        [StringLength(50)]
        public string AccName { get; set; }
        public int OpeningBalance { get; set; }
        public int Age30 { get; set; }
        public int Age60 { get; set; }
        public int Age90 { get; set; }
        public int Age120 { get; set; }
        public int Age121 { get; set; }
        public int CurBal { get; set; }
        [Required]
        [StringLength(50)]
        public string AccID { get; set; }
    }
}