// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewAllVouchers_VouchersDetail
    {
        public int VoucherCode { get; set; }
        public int? UserID { get; set; }
        public int? FrmValueVoucher { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateVoucher { get; set; }
        [StringLength(50)]
        public string FromAccID { get; set; }
        [Column(TypeName = "ntext")]
        public string VoucherDetails { get; set; }
        public bool? Done { get; set; }
        [Column(TypeName = "money")]
        public decimal? VoucherTotal { get; set; }
        [StringLength(20)]
        public string RefDocNo { get; set; }
        [StringLength(50)]
        public string RefDocDate { get; set; }
        public int? FinancialID { get; set; }
        public int? InvoiceNo { get; set; }
        public int? TypeDoc { get; set; }
        [Column(TypeName = "money")]
        public decimal? VoucherAmount { get; set; }
        [Column(TypeName = "ntext")]
        public string VoucherDescriptions { get; set; }
        [StringLength(50)]
        public string ToAccID { get; set; }
        [StringLength(100)]
        public string FromAccount { get; set; }
        [StringLength(100)]
        public string ToAccount { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        [StringLength(50)]
        public string MDDName { get; set; }
        public int? MDDFrmValue { get; set; }
        public int? CostCenterID { get; set; }
        public int? BankID { get; set; }
        [StringLength(50)]
        public string CheckNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckDate { get; set; }
        public int? VoucherID { get; set; }
        public int? BranchID { get; set; }
        public int FrmValue { get; set; }
        public int? MFrmValue { get; set; }
        [StringLength(100)]
        public string CostCenterName { get; set; }
        public int? SalesManCode { get; set; }
        [StringLength(100)]
        public string SalName { get; set; }
        public double? TaxAmountExp { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TaxNo { get; set; }
        public bool? TaxState { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        public double Total { get; set; }
    }
}