// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewPromotion
    {
        public int? OrderNo { get; set; }
        [StringLength(50)]
        public string OrderDate { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        public int? DepartmentID { get; set; }
        public int? CategoryID { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        [StringLength(100)]
        public string DepartmentNameA { get; set; }
        [StringLength(100)]
        public string DepartmentNameE { get; set; }
        [StringLength(100)]
        public string JobNameA { get; set; }
        [StringLength(100)]
        public string JobNameE { get; set; }
        [StringLength(100)]
        public string JobDescription { get; set; }
        public int? JobID { get; set; }
        public int? IDJobOld { get; set; }
        [StringLength(50)]
        public string CategoryNameA { get; set; }
        [StringLength(50)]
        public string CategoryNameE { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(100)]
        public string JobNameAO { get; set; }
        [StringLength(100)]
        public string JobNameEO { get; set; }
        [StringLength(100)]
        public string JobDescriptionO { get; set; }
        public int ID { get; set; }
        [StringLength(100)]
        public string MEmployeeNameA { get; set; }
        [StringLength(100)]
        public string MEmployeeNameE { get; set; }
    }
}