// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_ItemsJoin
    {
        public int BranchID { get; set; }
        public double? Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitSalesPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitMinSalesPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitWholePrice { get; set; }
        [StringLength(50)]
        public string UnitBarcode { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceCost { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceAverage { get; set; }
        public int ID { get; set; }
        [StringLength(50)]
        public string JoinItem { get; set; }
        public double? Quantity { get; set; }
        public int UnitID { get; set; }
        [Required]
        [StringLength(50)]
        public string ItemID { get; set; }
        public bool? HidePriceJoin { get; set; }
        public bool? HidePriceMain { get; set; }
    }
}