// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_FexidAssetsDepration
    {
        public int AssetID { get; set; }
        public int? AssetCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(100)]
        public string ProviderName { get; set; }
        [StringLength(50)]
        public string AssetNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PurchaseDate { get; set; }
        public double? PurchasePrice { get; set; }
        public int? AssetStats { get; set; }
        [StringLength(50)]
        public string DateRemove { get; set; }
        public double? AmountRemove { get; set; }
        [StringLength(50)]
        public string AccCashID { get; set; }
        public int? CostCenterID { get; set; }
        public bool? Done { get; set; }
        public int? UserID { get; set; }
        [StringLength(50)]
        public string AccDeID { get; set; }
        [StringLength(50)]
        public string AccExID { get; set; }
        public int? DepType { get; set; }
        public int? GroupNo { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public double? PerDep { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        [StringLength(50)]
        public string Location { get; set; }
        [StringLength(50)]
        public string DatestrartDep { get; set; }
        public double? RateM { get; set; }
        public double? AccAmount { get; set; }
        public double? PerAmount { get; set; }
        public double? NewAmount { get; set; }
        public double? BookAmount { get; set; }
        public double? AddAmount { get; set; }
        public double? SubAmount { get; set; }
        public bool? DoneD { get; set; }
        public double? FexidAmount { get; set; }
        public int? FinancialID { get; set; }
        public int? AssetNos { get; set; }
        public double? SubAmountValue { get; set; }
        [StringLength(50)]
        public string ToDateHi { get; set; }
        [StringLength(50)]
        public string FromDateHi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FromDate { get; set; }
    }
}