// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewPassport
    {
        [StringLength(50)]
        public string PassportA { get; set; }
        [StringLength(50)]
        public string PassportE { get; set; }
        [Required]
        [StringLength(50)]
        public string PassportNo { get; set; }
        [StringLength(50)]
        public string IssuPassportDate { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string IssuCountry { get; set; }
        [StringLength(100)]
        public string Notes { get; set; }
        [StringLength(50)]
        public string StratNewDate { get; set; }
        [StringLength(50)]
        public string EndNewDate { get; set; }
        public int? Period { get; set; }
        public int ID { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        public int? TypeID { get; set; }
        [StringLength(50)]
        public string StratNewDateG { get; set; }
        [StringLength(50)]
        public string EndNewDateG { get; set; }
        public int Active { get; set; }
        public double? AmountRenwal { get; set; }
        public double? AmountVist { get; set; }
    }
}