// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_CarsDatum
    {
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        public int? Active { get; set; }
        [StringLength(50)]
        public string StTypeNameE { get; set; }
        [StringLength(50)]
        public string StTypeNameA { get; set; }
        public int? Status { get; set; }
        public int? DepartmentID { get; set; }
        public int NoID { get; set; }
        [StringLength(50)]
        public string LicenseDate { get; set; }
        [StringLength(50)]
        public string PlantNo { get; set; }
        [StringLength(50)]
        public string SturchNo { get; set; }
        [StringLength(50)]
        public string TypeCar { get; set; }
        [StringLength(50)]
        public string ColorCar { get; set; }
        public int? ModelCar { get; set; }
        [StringLength(100)]
        public string Owner { get; set; }
        [StringLength(50)]
        public string StratFDate { get; set; }
        [StringLength(50)]
        public string EndFDate { get; set; }
        [StringLength(50)]
        public string StratIDate { get; set; }
        [StringLength(50)]
        public string EndIDate { get; set; }
        [StringLength(100)]
        public string InsCompany { get; set; }
        public double? InsAmount { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
    }
}