// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_Complex
    {
        [Required]
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? MDCodeGroup { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        public int? TypeItems { get; set; }
        public int? StatsItems { get; set; }
        public double? Qty { get; set; }
        public int UnitID { get; set; }
        public int BranchID { get; set; }
        public double? Quantity { get; set; }
        [StringLength(50)]
        public string JoinItem { get; set; }
        public int WareHouseID { get; set; }
        [StringLength(10)]
        public string ExpireDate { get; set; }
        public double? QuantityAv { get; set; }
        [StringLength(100)]
        public string MName { get; set; }
        [StringLength(100)]
        public string BWBrWaName { get; set; }
    }
}