// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewAllTranUser
    {
        [StringLength(100)]
        public string UserName { get; set; }
        public int? NameButton { get; set; }
        [StringLength(50)]
        public string TimeCreate { get; set; }
        [StringLength(50)]
        public string DateCreate { get; set; }
        public int ID { get; set; }
        public int? BranchID { get; set; }
        public int? TypeForm { get; set; }
        [Column(TypeName = "ntext")]
        public string DisForm { get; set; }
        public int? UserID { get; set; }
        public int? Expr1 { get; set; }
        [StringLength(50)]
        public string No { get; set; }
    }
}