// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewUnitItem
    {
        [Required]
        [StringLength(50)]
        public string ItemID { get; set; }
        [StringLength(100)]
        public string MName { get; set; }
        public int? MFrmValue { get; set; }
        public int MDCode { get; set; }
        public int BranchID { get; set; }
        public double? Qty { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        public int? TypeStock { get; set; }
    }
}