// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewAbsence
    {
        public int AbsenceID { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string AbsenceOrderStartDate { get; set; }
        public double? AbsenceAmount { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        [StringLength(50)]
        public string ReDate { get; set; }
        [StringLength(50)]
        public string AbsenceOrderEndDate { get; set; }
        public int? CountAbsentNo { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        public int? TypeID { get; set; }
    }
}