// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewDueDate
    {
        public int? PrCuID { get; set; }
        public int? InvoiceID { get; set; }
        public int? BranchID { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "money")]
        public decimal? Net { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        [StringLength(50)]
        public string ToAccID { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetTotal { get; set; }
        [StringLength(100)]
        public string PCName { get; set; }
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        public int? FrmValueVoucher { get; set; }
        public int? FrmValue { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? SalesManCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DueDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        public int MoveCode { get; set; }
        [StringLength(100)]
        public string Customer { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
    }
}