// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewUnit
    {
        public double? Qty { get; set; }
        [StringLength(100)]
        public string MName { get; set; }
        public int? MFrmValue { get; set; }
        [Required]
        [StringLength(50)]
        public string ItemID { get; set; }
        public int UnitID { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitSalesPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitWholePrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitMinSalesPrice { get; set; }
        [StringLength(50)]
        public string UnitBarcode { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceCost { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceAverage { get; set; }
        public int BranchID { get; set; }
        public int? MDCodeGroup { get; set; }
        public int? MDCodeUnit { get; set; }
        public int? TypeItems { get; set; }
        public int? StatsItems { get; set; }
        public int? MDCodeGroup4 { get; set; }
        public int? MDCodeGroup3 { get; set; }
        public int? MDCodeGroup2 { get; set; }
        public int? MDCodeGroup1 { get; set; }
        [Column(TypeName = "ntext")]
        public string Location { get; set; }
        public double? RequestQuantity { get; set; }
        public double? RequestPoint { get; set; }
        public int? ProfitSales { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceCostOpen { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceSalesman { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceMarket { get; set; }
        public int? StatsTax { get; set; }
        public double? TaxValue { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceAfterTax { get; set; }
        public int? MDPurUnit { get; set; }
        public int? MDSalUnit { get; set; }
        public int? TypeStock { get; set; }
    }
}