// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_PermissionExit
    {
        public int PermissionID { get; set; }
        [Required]
        [StringLength(50)]
        public string PermissionOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string PermissionOrderDate { get; set; }
        [StringLength(50)]
        public string FromTime { get; set; }
        [StringLength(50)]
        public string ToTime { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        public int? PermissionType { get; set; }
        public int? NoMinutes { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        public bool? PermissionDone { get; set; }
    }
}