// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewDedctionDetial
    {
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string DisOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string DisOrderDate { get; set; }
        [StringLength(50)]
        public string FromMonth { get; set; }
        [Column(TypeName = "money")]
        public decimal? InstallmentAmount { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        public bool? ChPaymentSalar { get; set; }
        [Column(TypeName = "money")]
        public decimal? InstallmentIn { get; set; }
        public bool? Done { get; set; }
        public int? DeductionType { get; set; }
        [StringLength(50)]
        public string FromMonthD { get; set; }
        [Column(TypeName = "money")]
        public decimal? InstallmentAmountD { get; set; }
        [Column(TypeName = "money")]
        public decimal? PaymentAm { get; set; }
        [Column(TypeName = "money")]
        public decimal? RemainAm { get; set; }
        [StringLength(50)]
        public string DeductionTypeNameA { get; set; }
        [StringLength(50)]
        public string DeductionTypeNameE { get; set; }
    }
}