// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewSumQuantityItem
    {
        [Required]
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? MDCodeGroup { get; set; }
        public int BranchID { get; set; }
        public double? Quantity { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        [StringLength(100)]
        public string Groups { get; set; }
        public int? MDCodeUnit { get; set; }
        public int MDCode { get; set; }
        [StringLength(100)]
        public string Units { get; set; }
        [StringLength(100)]
        public string BranchNAme { get; set; }
        public double? Qty { get; set; }
        [Column(TypeName = "money")]
        public decimal? PriceSales { get; set; }
        [Column(TypeName = "money")]
        public decimal? MinPrice { get; set; }
        [StringLength(50)]
        public string UnitBarcode { get; set; }
        [Column(TypeName = "money")]
        public decimal? WholePrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? PriceCost { get; set; }
        [Column(TypeName = "money")]
        public decimal? PriceAverage { get; set; }
    }
}