// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_ExpenssInvoice
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string AccIDExp { get; set; }
        public double? Amount { get; set; }
        public int? BranchID { get; set; }
        public int? UserID { get; set; }
        public int? TypeExp { get; set; }
        public int? TypeFrm { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        public int? FinancialID { get; set; }
        public int InvoiceCode { get; set; }
        public int? InvoiceID { get; set; }
        [StringLength(100)]
        public string PCName { get; set; }
        public int? FrmValue { get; set; }
        public int? CashierID { get; set; }
        public int? PayType { get; set; }
        [StringLength(50)]
        public string AccFund { get; set; }
        [StringLength(50)]
        public string AccExpName { get; set; }
        public int? CostCenterID { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public int? SalesManCode { get; set; }
        [StringLength(50)]
        public string TaxNo { get; set; }
        public double? TaxRatio { get; set; }
        public double? TaxAmount { get; set; }
    }
}