// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewMainDatum
    {
        public int? BWCode { get; set; }
        [StringLength(100)]
        public string MName { get; set; }
        [StringLength(50)]
        public string MNotes { get; set; }
        public int? MFrmValue { get; set; }
        [StringLength(50)]
        public string MAccID { get; set; }
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        public int MDCode { get; set; }
        public int MDCodeID { get; set; }
        public int? MBranchID { get; set; }
    }
}