// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewGetAllBarcode
    {
        [Required]
        [StringLength(50)]
        public string itemID { get; set; }
        public int UnitID { get; set; }
        public int BranchID { get; set; }
        [StringLength(50)]
        public string UnitBarcode { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        [StringLength(100)]
        public string MName { get; set; }
    }
}