// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewWarehouseItem
    {
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        [Required]
        [StringLength(50)]
        public string ItemID { get; set; }
        public int WareHouseID { get; set; }
        public double? QuantityIn { get; set; }
        public double? QuantityAv { get; set; }
        public int BranchID { get; set; }
    }
}