// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewPrintSalesman
    {
        [StringLength(100)]
        public string BranchName { get; set; }
        public int SalesManID { get; set; }
        public int SalesManCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(100)]
        public string SalName { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? TargetIncomeRequired { get; set; }
        public int? TargetSalesMonthly { get; set; }
        public int? CommissionType { get; set; }
        public int? CommissionValue { get; set; }
        public bool? CommissionOthers { get; set; }
        public int? CommissionOthersValue { get; set; }
        public int? HisWarhouse { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(100)]
        public string SalNameEng { get; set; }
        public int? Fund { get; set; }
    }
}