// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_AttendanceAutomated
    {
        [Required]
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [Required]
        [StringLength(20)]
        public string DateInsert { get; set; }
        [Required]
        [StringLength(20)]
        public string TimeInsert { get; set; }
        [StringLength(50)]
        public string ToTime { get; set; }
        [StringLength(50)]
        public string FromTime { get; set; }
        [StringLength(50)]
        public string Hourse { get; set; }
        public int? PeriodNo { get; set; }
        public double? HourseAll { get; set; }
        public double? AveBouns { get; set; }
        public double? AveAbsen { get; set; }
        public double? AveLeat { get; set; }
        public int? MuLeat { get; set; }
        [StringLength(50)]
        public string FromTime24 { get; set; }
        [StringLength(50)]
        public string ToTime24 { get; set; }
        public int? minutes { get; set; }
        public bool? Done { get; set; }
    }
}