// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewReconAndRecondetail
    {
        public int? DocNo { get; set; }
        [StringLength(50)]
        public string Date { get; set; }
        [Column(TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column(TypeName = "money")]
        public decimal? Credit { get; set; }
        [Column(TypeName = "ntext")]
        public string Description { get; set; }
        public bool? CamperDoc { get; set; }
        public int? BranchID { get; set; }
        public int? TypeCompare { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? UserID { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        [StringLength(50)]
        public string FromDate { get; set; }
        [StringLength(50)]
        public string ToDate { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        public int? FinancialID { get; set; }
        [StringLength(50)]
        public string AccName { get; set; }
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        public int RecCode { get; set; }
    }
}