// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_LoansForm
    {
        [Required]
        [StringLength(50)]
        public string LoanOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string LoanOrderDate { get; set; }
        [StringLength(50)]
        public string FromMonth { get; set; }
        public double? InstallmentAmount { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        public int? InstallmentIn { get; set; }
        public bool? Done { get; set; }
        public int ID { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        public int Active { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        public int? DepartmentID { get; set; }
        public int? ProfessionsID { get; set; }
        public int? CategoryID { get; set; }
        [StringLength(50)]
        public string JobID { get; set; }
    }
}