// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_TransferProduction
    {
        [Column(TypeName = "money")]
        public decimal? UnitSalesPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitMinSalesPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitWholePrice { get; set; }
        [StringLength(50)]
        public string UnitBarcode { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceCost { get; set; }
        [Column(TypeName = "money")]
        public decimal? UnitPriceAverage { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        public int? InvoiceCode { get; set; }
        public int? UnitID { get; set; }
        public int? WarehouseID { get; set; }
        public double? Quantity { get; set; }
        public double? QuantityBouns { get; set; }
        public double? QuantityFull { get; set; }
        public int? InvoiceID { get; set; }
        public int? CashierID { get; set; }
        public int? PrCuID { get; set; }
        public int? UserID { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DueDate { get; set; }
        [StringLength(50)]
        public string ProvInvNo { get; set; }
        [StringLength(50)]
        public string ProvInvDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? DiscountInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetInv { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        public bool? Done { get; set; }
        public int? PayType { get; set; }
        public int? UpdatePrice { get; set; }
        public int? OrderPurchase { get; set; }
        public int? FrmValue { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        public int? PriceID { get; set; }
        public int? QutationID { get; set; }
        [StringLength(50)]
        public string DateEnd { get; set; }
        public int? ReturnInvoiceID { get; set; }
        public int? SalesManCode { get; set; }
        public bool? BookMark { get; set; }
        [Column(TypeName = "money")]
        public decimal? PofitInvoice { get; set; }
        [Column(TypeName = "money")]
        public decimal? BonusPercent { get; set; }
        public int? CopyNo { get; set; }
        [StringLength(50)]
        public string TimeIN { get; set; }
        public int? CostCenterID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? CarID { get; set; }
        [StringLength(50)]
        public string ProductItem { get; set; }
        [Column(TypeName = "ntext")]
        public string NotesItem { get; set; }
        [Column(TypeName = "ntext")]
        public string SerialNo { get; set; }
        [StringLength(50)]
        public string OfferItem { get; set; }
        [Column(TypeName = "money")]
        public decimal? OtherPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? CostPrice { get; set; }
        public double? TotalDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        [StringLength(50)]
        public string ProductItemPOS { get; set; }
        [Column(TypeName = "money")]
        public decimal? CiTax { get; set; }
        public double? TaxPerItem { get; set; }
        [Column(TypeName = "money")]
        public decimal? CigaretTax { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? PriceBeforeTax { get; set; }
        [Column(TypeName = "money")]
        public decimal? OtherDiscount { get; set; }
        [StringLength(50)]
        public string ItemAccID { get; set; }
    }
}