// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewGaidEntry
    {
        public int MGID { get; set; }
        public int MoveID { get; set; }
        public int MoveCode { get; set; }
        public int? MoveSubCode { get; set; }
        public int? BranchID { get; set; }
        [StringLength(50)]
        public string TimeGa { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        public int? MoveGaidType { get; set; }
        public bool? Done { get; set; }
        public int? UserID { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitGaid { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditGaid { get; set; }
        public int? FinancialID { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        [StringLength(50)]
        public string MDDName { get; set; }
        public int? MDDFrmValue { get; set; }
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
    }
}