// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewWarwHouseRelted
    {
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        public int WarehouseID { get; set; }
        public int BranchID { get; set; }
        public int? BWType { get; set; }
        public bool? IsDefaultWare { get; set; }
    }
}