// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class View_ItemsProductionUnit
    {
        public int BranchID { get; set; }
        [StringLength(50)]
        public string ProductItem { get; set; }
        public int? UnitID { get; set; }
        [StringLength(50)]
        public string ItemID { get; set; }
        public double? Quantity { get; set; }
        public double? QuantityFull { get; set; }
        [Column(TypeName = "money")]
        public decimal? AP { get; set; }
        [Column(TypeName = "money")]
        public decimal? CP { get; set; }
        [StringLength(50)]
        public string UnitBarcode { get; set; }
        [Column(TypeName = "money")]
        public decimal? WP { get; set; }
        [Column(TypeName = "money")]
        public decimal? MP { get; set; }
        [Column(TypeName = "money")]
        public decimal? SP { get; set; }
        [Column(TypeName = "ntext")]
        public string Notes { get; set; }
        public int ID { get; set; }
        public double? Price { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        [StringLength(100)]
        public string Unit { get; set; }
        public int? MDCodeGroup { get; set; }
        public int? MDCodeUnit { get; set; }
        public int? TypeItems { get; set; }
        public int? StatsItems { get; set; }
        public int? MDCodeGroup1 { get; set; }
        public int? MDCodeGroup2 { get; set; }
        public int MDCode { get; set; }
        [StringLength(100)]
        public string Groups { get; set; }
        public int? MDCodeSubGroup { get; set; }
    }
}