// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewTicket
    {
        public int ID { get; set; }
        public int TicOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string TicOrderDate { get; set; }
        [StringLength(100)]
        public string LAddress { get; set; }
        public int? TicNo { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        public double? TicAmount { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
    }
}