// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewStatmentsBalance
    {
        public int MoveCode { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        [StringLength(20)]
        public string DocNo { get; set; }
        [StringLength(50)]
        public string DateGrD { get; set; }
        public int? GaneralType { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitLocal { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditLocal { get; set; }
        [StringLength(50)]
        public string TypeNameGaid { get; set; }
        public int Bal { get; set; }
    }
}