// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewAutoAttendance
    {
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [Required]
        [StringLength(20)]
        public string DateInsert { get; set; }
        [Required]
        [StringLength(20)]
        public string TimeInsert { get; set; }
        public int? Type { get; set; }
        public bool? Done { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        public int ID { get; set; }
        public int? DepartmentID { get; set; }
    }
}