// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewManagerDep
    {
        [StringLength(100)]
        public string DepartmentNameE { get; set; }
        [StringLength(100)]
        public string DepartmentNameA { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(100)]
        public string MEmployeeNameA { get; set; }
        [StringLength(100)]
        public string MEmployeeNameE { get; set; }
        [StringLength(50)]
        public string ManagerCode { get; set; }
        [StringLength(100)]
        public string JobNameA { get; set; }
        [StringLength(100)]
        public string JobNameE { get; set; }
        [StringLength(50)]
        public string HireDate { get; set; }
        public int DepartmentID { get; set; }
    }
}