// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewAllInvoice
    {
        public int InID { get; set; }
        public int InvoiceCode { get; set; }
        public int? InvoiceID { get; set; }
        public int? CashierID { get; set; }
        public int? BranchID { get; set; }
        public int? PrCuID { get; set; }
        public int? UserID { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DueDate { get; set; }
        [StringLength(50)]
        public string ProvInvNo { get; set; }
        [StringLength(50)]
        public string ProvInvDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateGr { get; set; }
        [StringLength(50)]
        public string DateHi { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? DiscountInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetInv { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        public bool? Done { get; set; }
        public int? UpdatePrice { get; set; }
        public int? PayType { get; set; }
        public int? OrderPurchase { get; set; }
        public int? FrmValue { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        public int? PriceID { get; set; }
        public int? QutationID { get; set; }
        public int? ReturnInvoiceID { get; set; }
        [StringLength(50)]
        public string DateEnd { get; set; }
        public int? SalesManCode { get; set; }
        public bool? BookMark { get; set; }
        [Column(TypeName = "money")]
        public decimal? PofitInvoice { get; set; }
        [Column(TypeName = "money")]
        public decimal? BonusPercent { get; set; }
        public int? CopyNo { get; set; }
        [StringLength(50)]
        public string TimeIN { get; set; }
        [StringLength(100)]
        public string SalName { get; set; }
        [StringLength(100)]
        public string BranchTo { get; set; }
        public int? ProviderCustomerCode { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [StringLength(100)]
        public string PCName { get; set; }
        public int? CostCenterID { get; set; }
        [StringLength(100)]
        public string Customer { get; set; }
        public int? CountryID { get; set; }
        public int? CityID { get; set; }
        [Column(TypeName = "money")]
        public decimal AmountVBank { get; set; }
        [Column(TypeName = "money")]
        public decimal AmountCash { get; set; }
        [Column(TypeName = "money")]
        public decimal RemainInv { get; set; }
        [Column(TypeName = "money")]
        public decimal PaymentInv { get; set; }
        [StringLength(50)]
        public string AccCheckID { get; set; }
        [StringLength(50)]
        public string AccCashID { get; set; }
        [StringLength(50)]
        public string CheckNo { get; set; }
        [StringLength(50)]
        public string CheckDate { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(200)]
        public string AddressSales { get; set; }
        [StringLength(50)]
        public string CardNoCustomer { get; set; }
        [StringLength(200)]
        public string AddressCustomer { get; set; }
        [Column(TypeName = "money")]
        public decimal? PaymentAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? RemainAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal ChangeAmount { get; set; }
        [StringLength(50)]
        public string MobileCustomer { get; set; }
        [StringLength(50)]
        public string AccChangeID { get; set; }
        [Column(TypeName = "money")]
        public decimal PointAmount { get; set; }
        public double ComissCard { get; set; }
        public double? NetInvFc { get; set; }
        public int? CurrencyID { get; set; }
        public double? Transfer { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        public int? CarID { get; set; }
        [StringLength(100)]
        public string MName { get; set; }
        public int? PointActive { get; set; }
        public int? DeliveryID { get; set; }
        public int? PostionID { get; set; }
        [StringLength(50)]
        public string EmployeeID { get; set; }
        [StringLength(50)]
        public string MNotes { get; set; }
        public int? TypeReturn { get; set; }
        public int? TypeOrderPos { get; set; }
        public int? TablePosNo { get; set; }
        public int? OrderPosNo { get; set; }
        public int? RetunChangeID { get; set; }
        [StringLength(50)]
        public string DateDelivery { get; set; }
        [StringLength(50)]
        public string TimeDelivery { get; set; }
        public int? BookingID { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        public double? PerTaxAmount { get; set; }
        [StringLength(100)]
        public string Expr1 { get; set; }
        [StringLength(50)]
        public string TaxNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? CigaretTax { get; set; }
        public double? PerCigaretTax { get; set; }
        public double? profit { get; set; }
        [StringLength(50)]
        public string PCTaxNo { get; set; }
        public int? e_InvNo { get; set; }
        public byte? e_InvType { get; set; }
        [Column(TypeName = "image")]
        public byte[] InvoiceQR { get; set; }
        public byte? e_InvStatus { get; set; }
        [StringLength(50)]
        public string FrmName { get; set; }
        [Column(TypeName = "money")]
        public decimal? RoundNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? AllwedDiscount { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountCashpay { get; set; }
        [Column(TypeName = "money")]
        public decimal? DiscountTotal { get; set; }
    }
}