// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewTrialBalance
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? BranchID { get; set; }
        public int? FinancialID { get; set; }
        [Column(TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column(TypeName = "money")]
        public decimal? Credit { get; set; }
        [StringLength(50)]
        public string DateGr { get; set; }
        [StringLength(50)]
        public string AccName { get; set; }
        public int? MainFinalAccount { get; set; }
        [StringLength(50)]
        public string MainAccountNo { get; set; }
        public int? LevelAccount { get; set; }
        public int? MainOrSub { get; set; }
        public int? CostCenterID { get; set; }
    }
}