// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewLeave
    {
        public int LeaveTypeID { get; set; }
        [StringLength(50)]
        public string LeaveTypeNameAr { get; set; }
        [StringLength(50)]
        public string LeaveTypeNameEn { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string LeaveOrderDate { get; set; }
        [StringLength(50)]
        public string LeaveStart { get; set; }
        [StringLength(50)]
        public string LeaveEnd { get; set; }
        [StringLength(100)]
        public string LAddress { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        public bool? LeaveDone { get; set; }
        public int LeaveOrderNo { get; set; }
        public double? CountDayLeave { get; set; }
        public bool? RetLeaveDone { get; set; }
        [StringLength(50)]
        public string ReDate { get; set; }
        public bool? ChLeaveYear { get; set; }
        [StringLength(250)]
        public string SAddress { get; set; }
        [StringLength(50)]
        public string SFax { get; set; }
        [StringLength(50)]
        public string SPhone { get; set; }
        [StringLength(100)]
        public string SName { get; set; }
        [StringLength(50)]
        public string NameProfessionsE { get; set; }
        [StringLength(50)]
        public string NameProfessionsA { get; set; }
        [StringLength(100)]
        public string BWBrWaName { get; set; }
        public int? BWCode { get; set; }
        public int? ProfessionsID { get; set; }
        [StringLength(100)]
        public string DepartmentNameA { get; set; }
        [StringLength(100)]
        public string DepartmentNameE { get; set; }
        public int Active { get; set; }
        public int? BloodType { get; set; }
        [StringLength(50)]
        public string BloodTypeName { get; set; }
        [StringLength(100)]
        public string JobDescription { get; set; }
        [StringLength(100)]
        public string JobNameE { get; set; }
        [StringLength(100)]
        public string JobNameA { get; set; }
        [StringLength(100)]
        public string MaritalStatusNameE { get; set; }
        [StringLength(100)]
        public string MaritalStatusNameA { get; set; }
        [StringLength(100)]
        public string ReligionNameE { get; set; }
        [StringLength(100)]
        public string ReligionNameA { get; set; }
        [StringLength(50)]
        public string StTypeNameA { get; set; }
        [StringLength(50)]
        public string StTypeNameE { get; set; }
        [StringLength(30)]
        public string CConNameEng { get; set; }
        [StringLength(30)]
        public string CConNameArb { get; set; }
        [StringLength(100)]
        public string QualificationNameE { get; set; }
        [StringLength(100)]
        public string QualificationNameA { get; set; }
        [StringLength(50)]
        public string GenderE { get; set; }
        [StringLength(50)]
        public string GenderA { get; set; }
        [StringLength(50)]
        public string AccIDO { get; set; }
        [StringLength(50)]
        public string AccIDE { get; set; }
        [StringLength(50)]
        public string AccIDDe { get; set; }
        [Column(TypeName = "image")]
        public byte[] EmpImage { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        public int? Status { get; set; }
        [Column(TypeName = "ntext")]
        public string PermissionString { get; set; }
        [StringLength(50)]
        public string JobID { get; set; }
        public int? CategoryID { get; set; }
        [StringLength(50)]
        public string HireDate { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        public int? DepartmentID { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        [StringLength(100)]
        public string SponsorAddress { get; set; }
        [StringLength(50)]
        public string SponsorPhone { get; set; }
        [StringLength(50)]
        public string Expr1 { get; set; }
        [StringLength(100)]
        public string SponsorNameID { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(100)]
        public string AddressE { get; set; }
        [StringLength(100)]
        public string AddressA { get; set; }
        [StringLength(50)]
        public string BankAccountNo { get; set; }
        [StringLength(50)]
        public string BankName { get; set; }
        [StringLength(50)]
        public string SocialInsurance { get; set; }
        [StringLength(50)]
        public string MedicalInsExpires { get; set; }
        [StringLength(50)]
        public string MedicalInsurance { get; set; }
        [StringLength(50)]
        public string DrivingLicExpires { get; set; }
        [StringLength(50)]
        public string DrivingLicNo { get; set; }
        [StringLength(50)]
        public string ResidenceExpires { get; set; }
        [StringLength(50)]
        public string ResidenceNo { get; set; }
        [StringLength(50)]
        public string NationalExpires { get; set; }
        [StringLength(50)]
        public string NationalNo { get; set; }
        [StringLength(50)]
        public string PassportExpires { get; set; }
        [StringLength(50)]
        public string PassportNo { get; set; }
        [StringLength(50)]
        public string Dependents { get; set; }
        public int? MaritalStatus { get; set; }
        public int? Nationality { get; set; }
        [StringLength(50)]
        public string Major { get; set; }
        public int? Qualification { get; set; }
        public int? ReligionID { get; set; }
        [StringLength(50)]
        public string DOBGR { get; set; }
        [StringLength(50)]
        public string DOBHI { get; set; }
        public int? GenderID { get; set; }
        [StringLength(30)]
        public string Passwords { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        public double? CountDayLeaveWork { get; set; }
        public double? Amount { get; set; }
        [StringLength(50)]
        public string DateAddPayment { get; set; }
        public int? TypePaymentID { get; set; }
        public bool? ChPayment { get; set; }
    }
}