// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewOhdum
    {
        [StringLength(100)]
        public string OhdaTypeNameA { get; set; }
        [StringLength(100)]
        public string OhdaTypeNameE { get; set; }
        public int OhdaOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string OhdaOrderDate { get; set; }
        public int? TypeOhdaID { get; set; }
        public int? OhdaNo { get; set; }
        [StringLength(100)]
        public string Notes { get; set; }
        public bool? RetOhdaDone { get; set; }
        public double? OhdaAmount { get; set; }
        [StringLength(50)]
        public string ReDate { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        public bool? Done { get; set; }
        public int ID { get; set; }
        [StringLength(50)]
        public string AccIDO { get; set; }
        [StringLength(50)]
        public string AccIDE { get; set; }
        [StringLength(50)]
        public string AccIDDe { get; set; }
        [StringLength(50)]
        public string AccFundID { get; set; }
        public int Active { get; set; }
    }
}