// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewSalesBalanceDueDate
    {
        public int? BranchID { get; set; }
        public int? FinancialID { get; set; }
        public int? PrCuID { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetS { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetR { get; set; }
        [Column(TypeName = "money")]
        public decimal? Net { get; set; }
    }
}