// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewSumVochersReceipt
    {
        public int? BranchID { get; set; }
        public int? FinancialID { get; set; }
        public int? InvoiceNo { get; set; }
        [StringLength(50)]
        public string ToAccID { get; set; }
        [Column(TypeName = "money")]
        public decimal? Amount { get; set; }
        public int ProviderCustomerID { get; set; }
        public int? FrmValueVoucher { get; set; }
        public int? FrmValueCust { get; set; }
        public int VoucherID { get; set; }
        public string Note { get; set; }
    }
}