// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewLoan
    {
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string LoanOrderNo { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(50)]
        public string LoanOrderDate { get; set; }
        [StringLength(50)]
        public string FromMonth { get; set; }
        [Column(TypeName = "money")]
        public decimal? InstallmentAmount { get; set; }
        [StringLength(100)]
        public string Note { get; set; }
        [Column(TypeName = "money")]
        public decimal? InstallmentIn { get; set; }
        public bool? ChPaymentSalar { get; set; }
        public bool? Done { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        public int? DepartmentID { get; set; }
        public int? CategoryID { get; set; }
        public int? Status { get; set; }
        [StringLength(50)]
        public string AccIDO { get; set; }
        [StringLength(50)]
        public string AccIDE { get; set; }
        [StringLength(50)]
        public string AccIDDe { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string AccFundID { get; set; }
        public int Active { get; set; }
        [StringLength(50)]
        public string AccIDL { get; set; }
    }
}