// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewAllInvoice_InvoiceDetailstemp
    {
        public int? ID { get; set; }
        public int? InvoiceCode { get; set; }
        [StringLength(3200)]
        public string ItemID { get; set; }
        public string ItemUnits { get; set; }
        public string ItemQty { get; set; }
        public int? UnitID { get; set; }
        public int? WarehouseID { get; set; }
        public double? Quantity { get; set; }
        public double? QuantityBouns { get; set; }
        public double? QuantityFull { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? DiscountDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetDetails { get; set; }
        [Column(TypeName = "money")]
        public decimal? CostPrice { get; set; }
        public int? QutationID { get; set; }
        public int? FinancialID { get; set; }
        public int? BranchID { get; set; }
        public int? FrmValue { get; set; }
        public int? PayType { get; set; }
        public int? InvoiceID { get; set; }
        [StringLength(3200)]
        public string DateGr { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        [StringLength(100)]
        public string ItemName { get; set; }
        [StringLength(100)]
        public string Unit { get; set; }
        [StringLength(100)]
        public string SalName { get; set; }
        [StringLength(100)]
        public string UserName { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? DiscountInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? NetInv { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        [StringLength(100)]
        public string BranchNameTo { get; set; }
        public int? PriceID { get; set; }
        [StringLength(3200)]
        public string DateEnd { get; set; }
        [StringLength(3200)]
        public string DueDate { get; set; }
        public int? ReturnInvoiceID { get; set; }
        public int? UpdatePrice { get; set; }
        [StringLength(100)]
        public string Warehouse { get; set; }
        public int? PrCuID { get; set; }
        public int? SalesManCode { get; set; }
        public int? CostCenterID { get; set; }
        [StringLength(3200)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string PhoneSa { get; set; }
        [StringLength(50)]
        public string MobileSa { get; set; }
        [StringLength(50)]
        public string PhoneCu { get; set; }
        public int? ProviderCustomerCode { get; set; }
        public int? MDCodeGroup { get; set; }
        [StringLength(100)]
        public string cashierName { get; set; }
        public double? ComissCard { get; set; }
        [Column(TypeName = "money")]
        public decimal? PointAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? ChangeAmount { get; set; }
        [StringLength(3200)]
        public string AccChangeID { get; set; }
        [Column(TypeName = "money")]
        public decimal? RemainAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? PaymentAmount { get; set; }
        [StringLength(3200)]
        public string CardNoCustomer { get; set; }
        [StringLength(4000)]
        public string AddressSales { get; set; }
        [StringLength(3200)]
        public string CheckDate { get; set; }
        [StringLength(3200)]
        public string CheckNo { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountVBank { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountCash { get; set; }
        [Column(TypeName = "money")]
        public decimal? RemainInv { get; set; }
        [Column(TypeName = "money")]
        public decimal? PaymentInv { get; set; }
        [StringLength(3200)]
        public string AccCheckID { get; set; }
        [StringLength(3200)]
        public string MobileCustomer { get; set; }
        [StringLength(3200)]
        public string AccCashID { get; set; }
        [StringLength(3200)]
        public string MobileSales { get; set; }
        [StringLength(4000)]
        public string NameSales { get; set; }
        [StringLength(3200)]
        public string TimeIN { get; set; }
        public double? Transfer { get; set; }
        public double? NetInvFc { get; set; }
        public int? CurrencyID { get; set; }
        [StringLength(50)]
        public string CurrencyName { get; set; }
        [StringLength(30)]
        public string CurrencyCode { get; set; }
        [StringLength(10)]
        public string CurrencyPart { get; set; }
        public int? LocalOrForiegn { get; set; }
        [StringLength(4000)]
        public string AddressCustomer { get; set; }
        [StringLength(4000)]
        public string PCName { get; set; }
        [StringLength(4000)]
        public string PCAddress { get; set; }
        [StringLength(3200)]
        public string MobileCu { get; set; }
        [Column(TypeName = "money")]
        public decimal? OtherPrice { get; set; }
        public int? BWCode { get; set; }
        [StringLength(100)]
        public string WarehouseTo { get; set; }
        [StringLength(100)]
        public string PrintName { get; set; }
        [Column(TypeName = "ntext")]
        public string OtherData { get; set; }
        [Column(TypeName = "ntext")]
        public string NotesItem { get; set; }
        [Column(TypeName = "ntext")]
        public string SerialNo { get; set; }
        [StringLength(3200)]
        public string ProductItem { get; set; }
        [StringLength(3200)]
        public string OfferItem { get; set; }
        public double Amount { get; set; }
        public int? CopyNo { get; set; }
        public int? OrderPurchase { get; set; }
        public bool? BookMark { get; set; }
        public int? CarID { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        public int? Active { get; set; }
        [StringLength(50)]
        public string StTypeNameE { get; set; }
        [StringLength(50)]
        public string StTypeNameA { get; set; }
        public int? Status { get; set; }
        public int? DepartmentID { get; set; }
        [StringLength(50)]
        public string LicenseDate { get; set; }
        [StringLength(50)]
        public string PlantNo { get; set; }
        [StringLength(50)]
        public string SturchNo { get; set; }
        [StringLength(50)]
        public string TypeCar { get; set; }
        [StringLength(50)]
        public string ColorCar { get; set; }
        public int? ModelCar { get; set; }
        [StringLength(100)]
        public string Owner { get; set; }
        [StringLength(50)]
        public string EndFDate { get; set; }
        [StringLength(50)]
        public string StratIDate { get; set; }
        [StringLength(50)]
        public string StratFDate { get; set; }
        [StringLength(50)]
        public string EndIDate { get; set; }
        [StringLength(100)]
        public string InsCompany { get; set; }
        public double? InsAmount { get; set; }
        [StringLength(3200)]
        public string DateHi { get; set; }
        [StringLength(100)]
        public string BranchCustomer { get; set; }
        [StringLength(50)]
        public string BranchMobile { get; set; }
        [StringLength(200)]
        public string BranchAddress { get; set; }
        [StringLength(50)]
        public string BranchPhone { get; set; }
        public int? CustomerID { get; set; }
        [StringLength(3200)]
        public string ProvInvNo { get; set; }
        [StringLength(3200)]
        public string ProvInvDate { get; set; }
        [StringLength(100)]
        public string AccNameStock { get; set; }
        [Column(TypeName = "money")]
        public decimal? BonusPercent { get; set; }
        public int? TypeReturn { get; set; }
        public int? TypeOrderPos { get; set; }
        public int? TablePosNo { get; set; }
        public int? OrderPosNo { get; set; }
        public int? PointActive { get; set; }
        public int? DeliveryID { get; set; }
        [StringLength(3200)]
        public string EmployeeID { get; set; }
        public int? PostionID { get; set; }
        public double? PerTaxAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        public int? BookingID { get; set; }
        [StringLength(3200)]
        public string TimeDelivery { get; set; }
        [StringLength(3200)]
        public string DateDelivery { get; set; }
        [Column(TypeName = "money")]
        public decimal? TaxDetails { get; set; }
        public double? TaxPerItem { get; set; }
        public double? TaxValue { get; set; }
        [StringLength(50)]
        public string BranchTax { get; set; }
        [StringLength(3200)]
        public string TaxNo { get; set; }
        public int PCType { get; set; }
        public int? CashierID { get; set; }
        public bool? Done { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(50)]
        public string PBox { get; set; }
        [StringLength(50)]
        public string Zip { get; set; }
        [Column(TypeName = "money")]
        public decimal? CigaretTax { get; set; }
        [StringLength(100)]
        public string PCNameEng { get; set; }
        [StringLength(200)]
        public string Expr1 { get; set; }
        [StringLength(100)]
        public string PCPerson { get; set; }
        [StringLength(50)]
        public string PCAccID { get; set; }
        [Column(TypeName = "money")]
        public decimal? CiTax { get; set; }
        [Column(TypeName = "ntext")]
        public string ItemNote { get; set; }
        public string ItemNotes { get; set; }
        public string NoteQty { get; set; }
        public string NotePrice { get; set; }
        [Column(TypeName = "ntext")]
        public string Barcode { get; set; }
        [StringLength(3200)]
        public string ProductItemPOS { get; set; }
        public string ItemBarcode { get; set; }
        [Column(TypeName = "image")]
        public byte[] InvoiceQR { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(50)]
        public string AddtionalNo { get; set; }
        [StringLength(50)]
        public string Expr2 { get; set; }
        [StringLength(30)]
        public string CConNameEng { get; set; }
        [StringLength(30)]
        public string CConNameArb { get; set; }
        [StringLength(50)]
        public string CityNameArb { get; set; }
        [StringLength(50)]
        public string CityNameEng { get; set; }
        public int? CityID { get; set; }
        [Column(TypeName = "money")]
        public decimal? RoundNo { get; set; }
        public byte? e_InvStatus { get; set; }
        [Column(TypeName = "money")]
        public decimal? AllwedDiscount { get; set; }
        [Column(TypeName = "money")]
        public decimal? AmountCashpay { get; set; }
        [StringLength(100)]
        public string GroupName { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalWithTax { get; set; }
        public double? StoneWeight { get; set; }
        public int? MDCodeSubGroup { get; set; }
        public double? TotalQty { get; set; }
        [StringLength(100)]
        public string SubGroupName { get; set; }
    }
}