// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewEmployessStatus
    {
        public int EmployeeID { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(100)]
        public string EmployeeNameA { get; set; }
        [StringLength(100)]
        public string EmployeeNameE { get; set; }
        [StringLength(30)]
        public string Passwords { get; set; }
        public int? GenderID { get; set; }
        [StringLength(50)]
        public string DOBHI { get; set; }
        [StringLength(50)]
        public string DOBGR { get; set; }
        public int? ReligionID { get; set; }
        public int? BloodType { get; set; }
        public int? Qualification { get; set; }
        [StringLength(50)]
        public string Major { get; set; }
        public int? Nationality { get; set; }
        public int? MaritalStatus { get; set; }
        [StringLength(50)]
        public string Dependents { get; set; }
        [StringLength(50)]
        public string PassportNo { get; set; }
        [StringLength(50)]
        public string PassportExpires { get; set; }
        [StringLength(50)]
        public string NationalNo { get; set; }
        [StringLength(50)]
        public string NationalExpires { get; set; }
        [StringLength(50)]
        public string ResidenceNo { get; set; }
        [StringLength(50)]
        public string ResidenceExpires { get; set; }
        [StringLength(50)]
        public string DrivingLicNo { get; set; }
        [StringLength(50)]
        public string DrivingLicExpires { get; set; }
        [StringLength(50)]
        public string MedicalInsurance { get; set; }
        [StringLength(50)]
        public string MedicalInsExpires { get; set; }
        [StringLength(50)]
        public string SocialInsurance { get; set; }
        [StringLength(50)]
        public string BankName { get; set; }
        [StringLength(50)]
        public string BankAccountNo { get; set; }
        [StringLength(100)]
        public string AddressA { get; set; }
        [StringLength(100)]
        public string AddressE { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(100)]
        public string SponsorName { get; set; }
        [StringLength(50)]
        public string SponsorPhone { get; set; }
        [StringLength(100)]
        public string SponsorAddress { get; set; }
        [StringLength(50)]
        public string BranchID { get; set; }
        public int? DepartmentID { get; set; }
        public int? ProfessionsID { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        [StringLength(50)]
        public string HireDate { get; set; }
        public int? CategoryID { get; set; }
        [StringLength(50)]
        public string JobID { get; set; }
        [Column(TypeName = "ntext")]
        public string PermissionString { get; set; }
        public int? Status { get; set; }
        [StringLength(50)]
        public string AccID { get; set; }
        [Column(TypeName = "image")]
        public byte[] EmpImage { get; set; }
        [StringLength(50)]
        public string AccIDDe { get; set; }
        [StringLength(50)]
        public string AccIDE { get; set; }
        [StringLength(50)]
        public string AccIDO { get; set; }
        public int Active { get; set; }
        public bool? ChType { get; set; }
    }
}