// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewChartOfCostCenterDetail
    {
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(112)]
        public string AccName { get; set; }
        public int? DocNo { get; set; }
        [StringLength(50)]
        public string TypeDoc { get; set; }
        public string Details { get; set; }
        [StringLength(50)]
        public string DateGrD { get; set; }
        [Column(TypeName = "money")]
        public decimal? DebitLocal { get; set; }
        [Column(TypeName = "money")]
        public decimal? CreditLocal { get; set; }
        [Column(TypeName = "money")]
        public decimal? Balance { get; set; }
        public int? GaneralType { get; set; }
        public int MoveID { get; set; }
        public int MoveCode { get; set; }
        [StringLength(100)]
        public string CostCenterName { get; set; }
        public int? FinancialID { get; set; }
        public int? BranchID { get; set; }
        public int? CostCenterID { get; set; }
    }
}