// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevExpressDemo.Models
{
    [Keyless]
    public partial class ViewTradingAccount
    {
        [Required]
        [StringLength(50)]
        public string AccID { get; set; }
        [StringLength(50)]
        public string AccName { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
        public int OpenBalance { get; set; }
        public int? MainFinalAccount { get; set; }
        public int Debit1 { get; set; }
        public int credit1 { get; set; }
        public int? LevelAccount { get; set; }
    }
}